### ISSUE TITLE
TypeError: 'int' object is not iterable. Maybe caused by an imcompatible version of sumo

### ISSUE THREAD

**Issue by Qian-Eric** [LucasAlegre/sumo-rl#1]
Hi, when I used sumo-1.1.0 to run this ql_single-intersection.py, it didn't work well. The version of my computer system is ubuntu 16.04, and the version of python is 3.5 which was created by Anaconda.

The traceback was reported by **traci**. So I wondered this error was caused by an imcompatible version of sumo.

Which version of sumo do you use?

I followed the tutorial in the readme and tried 

```bash
python ql_single-intersection.py 
```
but it told me ```-route``` is needed. So I tried the following command.

```bash
$ ~/Downloads/Compressed/sumo-rl-master$ python experiments/ql_single-intersection.py  -route nets/single-intersection/single-intersection.rou.xml
```
The error messages followed.

>WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
 Retrying in 1 seconds
/home/user/anaconda3/envs/py3_5/lib/python3.5/site-packages/gym/logger.py:30: UserWarning: WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
 Retrying in 1 seconds?UPS, TraCI: 3ms, vehicles TOT 0 ACT 0 BUF 0)           
Traceback (most recent call last):
  File "ql_single-intersection.py", line 68, in <module>
    initial_states = env.reset()
  File "/home/user/Downloads/Compressed/sumo-rl-master/sumo_rl/environment/env.py", line 105, in reset
    self.traffic_signals[ts] = TrafficSignal(self, ts, self.delta_time, self.min_green, self.max_green, self.phases)
  File "/home/user/Downloads/Compressed/sumo-rl-master/sumo_rl/environment/traffic_signal.py", line 31, in __init__
    traci.trafficlight.setCompleteRedYellowGreenDefinition(self.id, logic)
  File "/usr/share/sumo/tools/traci/_trafficlight.py", line 256, in setCompleteRedYellowGreenDefinition
    for p in tls.phases:
TypeError: 'int' object is not iterable
Step #0.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

**Comment by LucasAlegre** [comment]
Hello,

Thank you for the observation. I'm using SUMO v0.32.
It looks like they changed some Traci methods on v1.10 and both versions are not compatible. 
For now I will keep using v0.32, but change it for v1.10 is problably a matter of changing a few lines of code.

Regards,
Lucas

**Comment by ZhongmingGit** [comment]
Two versions of traci api are different.

Modify _sumo_rl/environment/traffic_signal.py", line 30, in init_
`logic = traci.trafficlight.Logic("new-program", 0, 0, 0, phases)` to `logic = traci.trafficlight.Logic("new-program", 0, 0, phases)`

and _sumo-rl/experiments/ql_single-intersection.py, line 53_
```
phases=[
                            traci.trafficlight.Phase(ns, ns, ns, "GGrr"),   # north-south
                            traci.trafficlight.Phase(2000, 2000, 2000, "yyrr"),
                            traci.trafficlight.Phase(we, we, we, "rrGG"),   # west-east
                            traci.trafficlight.Phase(2000, 2000, 2000, "rryy")
                            ])
```
to 
```
phases=[
                            traci.trafficlight.Phase(ns, "GGrr"),   # north-south
                            traci.trafficlight.Phase(2000, "yyrr"),
                            traci.trafficlight.Phase(we, "rrGG"),   # west-east
                            traci.trafficlight.Phase(2000, "rryy")
                            ])
```
could solve your problem

**Comment by Qian-Eric** [comment]
@ZhongmingGit  Thank you!

**Comment by BridgeQZH** [comment]
> Two versions of traci api are different.
> 
> Modify _sumo_rl/environment/traffic_signal.py", line 30, in init_
> `logic = traci.trafficlight.Logic("new-program", 0, 0, 0, phases)` to `logic = traci.trafficlight.Logic("new-program", 0, 0, phases)`
> 
> and _sumo-rl/experiments/ql_single-intersection.py, line 53_
> 
> ```
> phases=[
>                             traci.trafficlight.Phase(ns, ns, ns, "GGrr"),   # north-south
>                             traci.trafficlight.Phase(2000, 2000, 2000, "yyrr"),
>                             traci.trafficlight.Phase(we, we, we, "rrGG"),   # west-east
>                             traci.trafficlight.Phase(2000, 2000, 2000, "rryy")
>                             ])
> ```
> 
> to
> 
> ```
> phases=[
>                             traci.trafficlight.Phase(ns, "GGrr"),   # north-south
>                             traci.trafficlight.Phase(2000, "yyrr"),
>                             traci.trafficlight.Phase(we, "rrGG"),   # west-east
>                             traci.trafficlight.Phase(2000, "rryy")
>                             ])
> ```
> 
> could solve your problem

The code for now is different. But I also met this error when I tried to use that in colab. Do you know the reason?
