### ISSUE TITLE
Reward evaluation

### ISSUE THREAD

**Issue by DryCell-x** [LucasAlegre/sumo-rl#100]
Hello 

I am little bit confused about reward evaluation, is the evaluation is done every simulation seconds or after every action was taken (action in 5th second, reward evaluation in 6th second) or every next action is taken (reward evaluation is conducted at the same time next action is taken) ?

**Comment by LucasAlegre** [comment]
Hi,

The reward is computed at the same time the agents can select the next action.
t=0  [agents act]
t = t + delta_time  [reward is computed AND agents act again]

**Comment by DryCell-x** [comment]
Thank you very much!
