### ISSUE TITLE
No module named 'sumo_rl.environment'

### ISSUE THREAD

**Issue by smarianimore** [LucasAlegre/sumo-rl#101]
Hi everybody,
I'm trying to run a simple test using ray rllib, but after installation of all the (many!) dependencies, I get the following unexpected error upon running:

`from sumo_rl.environment.env import SumoEnvironment 
ModuleNotFoundError: No module named 'sumo_rl.environment'`

I did a simple `pip install sumo-rl` in the virtualenv where I have the project as per instructions but it seems something is wrong in the way the package is distributed via pip...

Can somebody help? Am I missing something on my side?
In the meanwhile I'll try to clone the repo and do a local pip installation...

Thanks in advance to anyone that would reply :)

**Comment by J9nZHANG** [comment]
If you use pycharm, I think that "Mark Directory as Source Root" may help you.

**Comment by smarianimore** [comment]
on my project directory? (thanks for taking your time to reply)

**Comment by LucasAlegre** [comment]
Hi, I'd recommend cloning the repo and running "pip install -e ." on it. Does it work for you?

The pypi version is a bit outdated now. I plan to update it in the next weeks.

**Comment by LiaoWC** [comment]
I have encountered that error before.
I'd suggest `pip install -e .`.
After I installed by this way, it works fine with my PyCharm.

**Comment by LucasAlegre** [comment]
This problem was solved in the last commit. The pypi version of the repository was outdated, and now it is working correctly.
