### ISSUE TITLE
stable_baselines module error -> 'gym.logger' has no attribute 'MIN_LEVEL'

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [LucasAlegre/sumo-rl#103]
Hello 
I got errors when running your models in a2c_2way-single-intersection.py
gym==0.22
sumo-rl==1.2
So i  changed the "MIN_LEVEL" in stable_baselines.common.base_class.py into "min_level" to run your model

**Comment by TrinhTuanHung2021** [comment]
No module named 'linear_rl' when running sarsa_2way-single-intersection.py

I can not install linear_rl

**Comment by LucasAlegre** [comment]
Hi, stable-baselines have not been updated for years now. I am removing this example, and I suggest using stable-baselines3 in its place.

linear_rl can be found at https://github.com/LucasAlegre/linear-rl
