### ISSUE TITLE
How to evaluate the performance of training process

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [LucasAlegre/sumo-rl#104]
Hello. Thank you very much for your models.
I have just run your model 
`python experiments/a2c_2way-single-intersection.py`

 i changed num_seconds=3600 to measure the total waiting time in 1 hour
and changed total_timesteps=30000 to reduce training time.
My outputs have 41 episodes and I run
`python outputs/plot.py -f outputs/2way-single-intersection/a2c`

![Figure_1](https://user-images.githubusercontent.com/82990411/184808913-8afb50f2-eae0-46a8-a178-9f2685071721.png)

I see that this is only the total waiting time in the model over time ( 1 hour) and it did not show the performance of the training process. I would like to ask you if there is any way to show the total waiting time after 41 episodes.
Thank you verry much

**Comment by TrinhTuanHung2021** [comment]
For example, in your graph
![Figure_1](https://user-images.githubusercontent.com/82990411/184809521-45354cfb-1db7-4678-bf1a-4c616d3410b7.png)

you showed that the total waiting time decreased after the training process and this graph expressed the relationship between total time and total time steps. But in your coding files, it changed total_timesteps to num_seconds. So i can not evaluate the modes after training

**Comment by LucasAlegre** [comment]
You should specify which episode you want to plot:

python outputs/plot.py -f outputs/2way-single-intersection/a2c_run0.csv
or
python outputs/plot.py -f outputs/2way-single-intersection/a2c_run42.csv
so on

**Comment by TrinhTuanHung2021** [comment]
> You should specify which episode you want to plot:
> 
> python outputs/plot.py -f outputs/2way-single-intersection/a2c_run0.csv or python outputs/plot.py -f outputs/2way-single-intersection/a2c_run42.csv so on

Thank you for your quick reply!
And  I could get 2 episodes 
Episode 1:
![1](https://user-images.githubusercontent.com/82990411/184875264-e8275dde-2883-4907-9c6b-e65f5fe70a3d.png)

And Episode 41
![42](https://user-images.githubusercontent.com/82990411/184875328-5ca10b55-4457-40e4-9ef4-1a85eb0b838e.png)

But i want to combine them in 1 graph like yours.
