### ISSUE TITLE
Agent stuck using the same action throughout simulation

### ISSUE THREAD

**Issue by Sitting-Down** [LucasAlegre/sumo-rl#105]
Hello I've been trying to use sumo-rl as a Multi-Agent training tool for DQN to try and understand and explore RLlib
but I've noticed that after a certain point the agent gets stuck using a certain action causing one portion of the road to accumulate, even with a negative reward associated with that move. Every single agent exhibits this tendency but at different time steps.
I tried using Pressure and Diff-waiting time and ive attached the diff-waiting output below
![image](https://user-images.githubusercontent.com/105152125/185236667-0d34225b-7be1-415f-b09b-be5f29400929.png)
![image](https://user-images.githubusercontent.com/105152125/185236861-1599e532-9ed0-41fb-8c18-5dc48be80795.png)
![image](https://user-images.githubusercontent.com/105152125/185236984-0929cf64-24ae-4fa8-9f6c-040eda427a7e.png)

Here is the code ive been using and ive only edited the get_per_agent_info to include other things I thought i might need to see
https://pastebin.com/cttz6xSw

Could you point me to where I might have gone wrong or possible fix for situations like this
Thank you

**Comment by Sitting-Down** [comment]
Ive narrowed down the issue to be with the train.evaluate or specifically, when evaluating the policy it outputs very bad data and im not quite sure why.

The train only model outputs 290,000 cars but when evaluating it only outputs 180,000 because it gets stuck into only doing the one action.

**Comment by Sitting-Down** [comment]
I think that the issue when i start evaluating the policy, 
it doesnt have any of the observations used in the training is what i assume is happening. 

Thats why it gets stuck using the same action
as when you try to evaluate in the rllib dqn trainer it sets the explore to false.

But im confused because doesnt the training give the observations and actions to the policy? hence the padded_action and padded_observation?

is it possible to ask for some help?

**Comment by eonr** [comment]
@Sitting-Down Hey, I'm having the same problem during evaluation. Were you able to find out what's causing this?
