### ISSUE TITLE
Starting the environment and everything needs to be done 

### ISSUE THREAD

**Issue by btopii32** [LucasAlegre/sumo-rl#107]
Hey guys, I'm having a bit of trouble trying to start using this sumo-rl framework. I've created a virtual environment using anaconda and installed the framework using pip. It's done now but I don't know what else to do. Been reading around the documentation but it still does feel like I need to know more. Any help please?
I've built my network already with sumo netedit and I want to use reinforment learning to control the traffic phases and reduce total wait times of vehicles.

**Comment by LucasAlegre** [comment]
Have you checked the examples scripts? It shouldn't be much more to do than replacing the name of the net and route files for yours and choosing a RL library / algorithm to use.

**Comment by btopii32** [comment]
Oh okay. Which algorithm is the best per my project please?   I want to use reinforment learning to control the traffic phases and reduce total wait times of vehicles.
