### ISSUE TITLE
traci error

### ISSUE THREAD

**Issue by zzcNEU** [LucasAlegre/sumo-rl#11]
hello,I have try to run it! And i try to run the ql_single.....  ,
 But, it seams like sumo have some problem.Can you help me?

![image](https://user-images.githubusercontent.com/38434094/82304567-182c2080-99ef-11ea-84c8-d15b22091fab.png)

**Comment by sxyd** [comment]
You may need to check your netfile path, and set the value of self._net to the correct path.

**Comment by zzcNEU** [comment]
> You may need to check your netfile path, and set the value of self._net to the correct path.

hello,Now I can run it completely！Thanks your reply!
And I have another question. 
The coder set the num_seconds=100000,What does it mean？
How long does it take to run it once?

**Comment by zzcNEU** [comment]
> > 您可能需要检查您的netfile路径，并将self._net的值设置为正确的路径。
> 
> 您好，现在我可以完全运行它了！谢谢您的回复！
> 我还有另一个问题。
> 编码器设置了num_seconds = 100000，这是什么意思？
> 运行一次需要多长时间？
