### ISSUE TITLE
Have you considered using environment.yml or requirements.txt?

### ISSUE THREAD

**Issue by kourouklides** [LucasAlegre/sumo-rl#111]
Did it ever cross your mind to use an `enivronment.yml` or at least a `requirements.txt` file? Or is it a local custom in your country not to include versions of each specific Python library / framework? 😜

I understand that you're using the [setup.py](https://github.com/LucasAlegre/sumo-rl/blob/master/setup.py) file to install it from source; however, you did _not_ include **_all_** the specific versions at [line 3](https://github.com/LucasAlegre/sumo-rl/blob/master/setup.py#L3).

### **Suggestion**
Including all versions could have been useful. Including a `requirements.txt` would've been more useful. Including an `enivronment.yml` would've been even more useful. Using Docker would have been the ultimate solution. Please don't expect your users to use trial-and-error to find the version of each specific dependency.

`pip freeze` is your friend. 😉

**Comment by LucasAlegre** [comment]
Hi @kourouklides,

`REQUIRED = ['gym>=0.25', 'numpy', 'pandas', 'pillow', 'pettingzoo==1.18.1', 'sumolib', 'traci']`

The only important version constraint requirements are gym and pettingzoo. All other libraries work with any versions.

Is there a specific dependency that you had trouble with?

Thank you for the suggestion!

**Comment by kourouklides** [comment]
Actually, **_yes_**. I have problem with all the dependencies. First of all, what is the exact version of Python that you have used for your version (using pip)? Was it `Python 3.6.5` or something else? I could not find it anywhere in your instractions.

**Comment by LucasAlegre** [comment]
Hi,

We support Python>=3.7, just as Gym. I have just updated the setup.py file. I was able to create a new conda env and install everything by simply running `pip install -e .`

What problems do you have?

**Comment by kourouklides** [comment]
### **Input**

```
$ python ql_single-intersection.py 
```

### **Output**

```
Warning: Gym version v0.24.0 has a number of critical issues with `gym.make` such that the `reset` and `step` functions are called before returning the environment. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1
Traceback (most recent call last):
  File "ql_single-intersection.py", line 47, in <module>
    max_green=args.max_green)
  File "/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/sumo_rl/environment/env.py", line 125, in __init__
    traci.start([sumolib.checkBinary('sumo'), '-n', self._net], label='init_connection'+self.label)
  File "/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py", line 150, in start
    sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
  File "/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sumo': 'sumo'
(sumo_rl_pip) kourouklides:Downloads Ioannis$ python dqn_big-intersection.py 
Warning: Gym version v0.24.0 has a number of critical issues with `gym.make` such that the `reset` and `step` functions are called before returning the environment. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1
Traceback (most recent call last):
  File "dqn_big-intersection.py", line 14, in <module>
    from stable_baselines3.dqn.dqn import DQN
ModuleNotFoundError: No module named 'stable_baselines3'
```

**Comment by LucasAlegre** [comment]
SUMO-RL is a repository for providing the RL environments, not RL algorithms.

The examples folders contain examples of how to use SUMO-RL with some known RL algorithms libraries. However, these libraries are not SUMO-RL dependencies. Check the documentation of the specific RL library you want to use if you have trouble with the learning algorithms.

**Comment by kourouklides** [comment]
It's not clear what you're trying to say. In any case, do you have any example code that your repository is intended to run? 

PS. The problem seems to be with your repository and not the "RL algorithms". You're missing dependencies.

**Comment by kourouklides** [comment]
Anyway, I managed to resolve the dependencies by myself.

Is this a code that your repository is intended to run? It was taken from [README.md](https://github.com/LucasAlegre/sumo-rl/blob/master/README.md#pettingzoo-multi-agent-api).

### **Input**

```
>>> env = sumo_rl.env(net_file='sumo_net_file.net.xml', route_file='sumo_route_file.rou.xml', use_gui=True, num_seconds=3600)
```

### **Output**

```
 Retrying in 1 seconds
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
  Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
  Reason: image not found
/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60396 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
 Retrying in 1 seconds
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
  Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
  Reason: image not found
/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60399 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
 Retrying in 1 seconds
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
  Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
  Reason: image not found
/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60402 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
 Retrying in 1 seconds
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
  Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
  Reason: image not found
/Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60405 (TraCI server already finished). Retrying with different port.
  " Retrying with different port.") % (sumoPort, e))
```

(... and keeps looping continuously with the same error)

**Comment by LucasAlegre** [comment]
> It's not clear what you're trying to say. In any case, do you have any example code that your repository is intended to run?
> PS. The problem seems to be with your repository and not the "RL algorithms". You're missing dependencies.

SUMO-RL is repository of Gym and PettingZoo environments. It IS NOT a repository for running RL algorithms. Stable-baselines,  RLlib, etc. ARE NOT SUMO-RL dependencies, and should not be installed by default when installing SUMO-RL.

An example of running a Tabular QL agent can be found here:
See https://github.com/LucasAlegre/sumo-rl/blob/master/experiments/ql_4x4grid.py

**Comment by LucasAlegre** [comment]
> Anyway, I managed to resolve the dependencies by myself.
> 
> Is this a code that your repository is intended to run? It was taken from [README.md](https://github.com/LucasAlegre/sumo-rl/blob/master/README.md#pettingzoo-multi-agent-api).
> 
> ### **Input**
> ```
> import sumo_rl
> env = sumo_rl.env(net_file='sumo_net_file.net.xml', route_file='sumo_route_file.rou.xml', use_gui=True, num_seconds=3600)
> ```
> 
> ### **Output**
> ```
>  Retrying in 1 seconds
> dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
>   Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
>   Reason: image not found
> /Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60396 (TraCI server already finished). Retrying with different port.
>   " Retrying with different port.") % (sumoPort, e))
>  Retrying in 1 seconds
> dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
>   Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
>   Reason: image not found
> /Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60399 (TraCI server already finished). Retrying with different port.
>   " Retrying with different port.") % (sumoPort, e))
>  Retrying in 1 seconds
> dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
>   Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
>   Reason: image not found
> /Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60402 (TraCI server already finished). Retrying with different port.
>   " Retrying with different port.") % (sumoPort, e))
>  Retrying in 1 seconds
> dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.25.dylib
>   Referenced from: /usr/local/Cellar/sumo/1.14.1/share/sumo/bin/sumo
>   Reason: image not found
> /Applications/anaconda3/envs/sumo_rl_pip/lib/python3.7/site-packages/traci/main.py:160: UserWarning: Could not connect to TraCI server using port 60405 (TraCI server already finished). Retrying with different port.
>   " Retrying with different port.") % (sumoPort, e))
> ```
> 
> (... and keeps looping continuously with the same error)

You should replace net_file='sumo_net_file.net.xml', route_file='sumo_route_file.rou.xml' with actual existing files. A few networks and route files are available on nets folds.
