### ISSUE TITLE
Environment sumo-rl doesn't exist.

### ISSUE THREAD

**Issue by kurkurzz** [LucasAlegre/sumo-rl#114]
```py
import gym
import sumo_rl
env = gym.make('sumo-rl-v0',
                net_file='path_to_your_network.net.xml',
                route_file='path_to_your_routefile.rou.xml',
                out_csv_name='path_to_output.csv',
                use_gui=True,
                num_seconds=100000)
```
I got the error when running the code provided in the documentation. 
I already:
- Installed the latest version of SUMO
- Installed gym=="0.24.0"

Do I need to register sumo-rl env somewhere?

**Comment by firemankoxd** [comment]
I've had a same issue, try running `python setup.py` in sumo-rl folder, hopefully that helps

**Comment by kurkurzz** [comment]
Run where exactly? I tried running it in the `sumo-rl` folder that is located in the `site-packages`. 
Command `python setup.py` gives an error `[Errno 2] No such file or directory`.

My `sumo-rl` folder:
![image](https://user-images.githubusercontent.com/64152220/194097820-2762cce8-3bbb-49d1-9415-a9e9260575ea.png)

**Comment by kurkurzz** [comment]
Running `python setup.py` will prompt this error:
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

I also tried running `python setup.py install`, it is still not registered to gym

**Comment by LucasAlegre** [comment]
The README has instructions on how to install the repo:

git clone https://github.com/LucasAlegre/sumo-rl
cd sumo-rl
pip install -e .
