### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by TailongSong202064524** [LucasAlegre/sumo-rl#128]
File "D:\anaconda\envs\PyTorch\lib\site-packages\stable_baselines3\common\base_class.py", line 172, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) as action spaces but Discrete(2) was provided

I need some help.
I want to know how to solve this problem

**Comment by TailongSong202064524** [comment]
In another experiment，a3c_4x4grid

File "\sumo-rl-master\sumo_rl\environment\env.py", line 28, in env
    env = wrappers.AssertOutOfBoundsWrapper(env)
  File "D:\anaconda\envs\PyTorch\lib\site-packages\pettingzoo\utils\wrappers\assert_out_of_bounds.py", line 13, in __init__
    assert all(isinstance(self.action_space(agent), Discrete) for agent in getattr(self, 'possible_agents', [])), "should only use AssertOutOfBoundsWrapper for Discrete spaces"
AssertionError: should only use AssertOutOfBoundsWrapper for Discrete spaces



I'm not sure whether the signal light design is wrong in my sumo file

**Comment by Nyphet** [comment]
Are you using the latest version of sumo_rl along with the latest stable version of stable_baselines3? If so, trying installing stable_baselines3 from this: git+https://github.com/DLR-RM/stable-baselines3@feat/gymnasium-support (for instance the command with pip would be `pip3 install git+https://github.com/DLR-RM/stable-baselines3@feat/gymnasium-support`)
