### ISSUE TITLE
single-intersection：Numpy RuntimeWarning

### ISSUE THREAD

**Issue by xu46** [LucasAlegre/sumo-rl#129]
When I run the following code：
**import gymnasium as gym
import sumo_rl
env = gym.make('sumo-rl-v0',
                net_file = r'D:\pycharm project\sumo_rl\sumorl-master\nets\single-intersection\single-intersection.net.xml',
                route_file = r'D:\pycharm project\sumo_rl\sumorl-master\nets\single-intersection\single-intersection.rou.xml',
                out_csv_name = '12output.csv',
                use_gui = True,
                num_seconds = 3600)
obs, info = env.reset()
done = False
while not done:
    next_obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
    done = terminated or truncated**

The following warning appears that sumo can continue to run, but there is no data in the csv file：
**C:\Users\23695\anaconda3\python.exe "D:/pycharm project/sumo_rl/test 1.py"
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 3ms, vehicles TOT 0 ACT 0 BUF 0)                      
C:\Users\23695\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\23695\anaconda3\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)**

**Comment by LucasAlegre** [comment]
Hi, the code with the error does not seem to come from the code you pasted. Can you share the full code?

**Comment by xu46** [comment]
Hi, my full code is in the picture below：
![QQ图片20230218152708](https://user-images.githubusercontent.com/97817334/219847675-ffd2332b-b97e-4c12-ba94-2c95e65813c4.png)
Here are the problems and errors that occur on the console after running the code：
![QQ图片20230218152506](https://user-images.githubusercontent.com/97817334/219847526-a38d07d4-75f6-4f55-b396-c661d248ab64.png)
The problem I have is that sumogui works fine, but the output csv file is empty, and numpy has a warning that my version of numpy is faulty.My environment is as follows：
ca-certificates | 2023.01.10 |  
certifi | 2022.12.7 |  
cloudpickle | 2.2.1 |  
cycler | 0.11.0 |  
fonttools | 4.38.0 |  
gymnasium | 0.27.0 |  
gymnasium-notices | 0.0.1 |  
importlib-metadata | 6.0.0 |  
jax-jumpy | 0.2.0 |  
kiwisolver | 1.4.4 |  
matplotlib | 3.5.3 |  
numpy | 1.21.6 |  
openssl | 1.1.1t |  
packaging | 23.0 |  
pandas | 1.3.5 |  
pettingzoo | 1.22.2 |  
pillow | 9.4.0 |  
pip | 22.3.1 |  
pyparsing | 3.0.9 |  
python | 3.7.16 |  
python-dateutil | 2.8.2 |  
pytz | 2022.7.1 |  
seaborn | 0.12.2 |  
setuptools | 65.6.3 |  
shimmy | 0.2.0 |  
six | 1.16.0 |  
sqlite | 3.40.1 |  
sumo-rl | 1.4.0 |  
sumolib | 1.16.0 |  
traci | 1.16.0 |  
typing-extensions | 4.4.0 |  
vc | 14.2 |  
vs2015_runtime | 14.27.29016 |  
wheel | 0.37.1 |  
wincertstore | 0.2 |  
zipp | 3.13.0 |

**Comment by LucasAlegre** [comment]
Hi!

1) The numpy warnings were not the cause of the error. I have just removed them in the last commit, but they could be safely ignored.
2) To save the output file, you need to call env.save_csv()
3) The error you are having seems to be caused by Windows when calling traci.close(). I don't know what causes the error, but it does not occur on Linux. I suggest you ask for help on https://github.com/eclipse/sumo .

**Comment by xu46** [comment]
Ok, thank you for your help.
