### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.testing.decorators'

### ISSUE THREAD

**Issue by anerudhr** [LucasAlegre/sumo-rl#13]
Hi, I ran into this issue above when I tried: python experiments/a3c_2way-single-intersection.py . I looked up solutions online, which suggested changing the version of numpy used, tried that but the issue persists. Please help me out.

**Comment by anerudhr** [comment]
Ok, I downgraded numpy to an even older version still, now I don't get this error. Thanks anyway.

**Comment by anerudhr** [comment]
Initially I used numpy 1.19, downgraded it to numpy 1.18, then 1.17, finally 1.16 worked.

**Comment by LucasAlegre** [comment]
Hi, can you say what was the error?

**Comment by anerudhr** [comment]
Hi! I guess numpy 1.18, the version installed earlier, doesn't have this
module.  





On Wed, Jul 8, 2020 3:32 PM, Lucas Alegre notifications@github.com  wrote:


Hi, can you say what was the error?

**Comment by anerudhr** [comment]
PS- I finally install  numpy 1.16 which is working fine now. Also, can I run
the trained model on live data? If so, how? Say, I can count the number of cars
at an intersection via some sensors.  





On Wed, Jul 8, 2020 3:32 PM, Lucas Alegre notifications@github.com  wrote:


Hi, can you say what was the error?

**Comment by anerudhr** [comment]
Hi,Hope you are doing well. The README.md is quite short and I have quite a
few queries regarding this. Please help me out.
Regards,Anerudh  





On Wed, Jul 8, 2020 3:46 PM, Anerudh Raina yansraj@gmail.com  wrote:
PS- I finally install  numpy 1.16 which is working fine now. Also, can I run the
trained model on live data? If so, how? Say, I can count the number of cars at
an intersection via some sensors.  





On Wed, Jul 8, 2020 3:32 PM, Lucas Alegre notifications@github.com  wrote:


Hi, can you say what was the error?

**Comment by anerudhr** [comment]
PS- Suppose I want to see the trained model in action, or if I want to see the
performance on live data. Even better, train and test on live data. Please help
me out.  





On Wed, Jul 8, 2020 3:46 PM, Anerudh Raina yansraj@gmail.com  wrote:
PS- I finally install  numpy 1.16 which is working fine now. Also, can I run the
trained model on live data? If so, how? Say, I can count the number of cars at
an intersection via some sensors.  





On Wed, Jul 8, 2020 3:32 PM, Lucas Alegre notifications@github.com  wrote:


Hi, can you say what was the error?
