### ISSUE TITLE
_compute_dones wrong?

### ISSUE THREAD

**Issue by Nyphet** [LucasAlegre/sumo-rl#132]
Hi, I noticed that in the SumoEnvironment code there's written "episode ends when sim_step >= max_steps", however inside _compute_dones the condition is only "self.sim_step > self.sim_max_time", missing the =.  
Is this intended (and if yes, why > instead of >=?)?  
If it's not intended, would you mind updating the code so that installing the library via pip will have the updated code?  
Thanks.

**Comment by LucasAlegre** [comment]
Hi @Nyphet,

Thanks for noticing that! I fixed this and released version 1.4.1 with the updated code :)
