### ISSUE TITLE
default output files

### ISSUE THREAD

**Issue by stephenlp** [LucasAlegre/sumo-rl#136]
Hi, I wonder how can we add the argument to generate default output such as tripinfo, summary, etc,
Usually this is configured in the sumocfg file as :

    <output>
	  <tripinfo-output value="tripinfo.xml"/>
    </output>
    
 looking forward to hearing any help. Thanks a lot!

**Comment by LucasAlegre** [comment]
Hi, you can do that by passing the corresponding command (https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html) to `additional_sumo_cmd` parameter in the constructor:
```
env = gym.make('sumo-rl-v0',
                ...
                additional_sumo_cmd="--tripinfo-output tripinfo.xml"
 )
```

**Comment by stephenlp** [comment]
Thanks a lot for your reply, Lucas!

One more thing that I wonder about. In ql Single intersection example, for every iteration (runs), we reload the QLAgent. Does that mean that for every run, the agent is reset? Because I tried to run it 1 time vs 10 times (runs), and the result with only 1 run is somehow better than with 10 runs. 

Hope you can help clarify. Thanks a lot:)

**Comment by LucasAlegre** [comment]
Yes, the agent is reset every run, so this result is expected. With the default observation space, the number of discretized states maybe be too big for tabular Q-learning. To achieve good results, you may need to increase the simulation time, or change the observation in a way to reduce the number of states.

**Comment by stephenlp** [comment]
Thank you!
