### ISSUE TITLE
About sumo_cmd

### ISSUE THREAD

**Issue by Metro1998** [LucasAlegre/sumo-rl#139]
Hello, thanks for this excellent work!
And I want to know where should I go if I want to find the complete sumo cmd definition.
for example https://github.com/LucasAlegre/sumo-rl/blob/a0d25ce4100c978d71667ec021761e13116bb8a5/sumo_rl/environment/env.py#L199-L208
To be more specific, I want to know how to load additional.xml through sumo_cmd, but it seems '-a' doesn't work at all.

**Comment by LucasAlegre** [comment]
Hi!

You can add additional commands via the `additional_sumo_cmd` argument of the constructor:
```
env(...
      additional_sumo_cmd="-a file"
)
```

**Comment by Metro1998** [comment]
Actually, I have found the web page regard the sumo cmd definition, https://sumo.dlr.de/docs/sumo.html#Loading_order_of_input_files, and "-a" does work, and there is a bug in my add.xml so that the program crash.
But thanks for your reply and excellent work any way, which does help me lot.

**Comment by LucasAlegre** [comment]
I'm glad to help!
