### ISSUE TITLE
info dicts not returning populated with metrics in multiagent api

### ISSUE THREAD

**Issue by miked131** [LucasAlegre/sumo-rl#140]
Hi, I'm testing some multiagent resco scenarios, just using the random action multiagent example code from the front page so far. I'm finding on the step function that the infos dictionary is being returned populated with the agent names as keys, but their corresponding dicts are empty. 

I have tried setting 'add_per_agent_info=True' and 'add_system_info=True' when initializing the env with no result. 

Screenshot from the cologne3 scenario after ~100 steps with 'add_per_agent_info=True' is attached 
![image](https://user-images.githubusercontent.com/110704756/231477368-3f942dea-1a85-4f86-9cb6-39361bb673d1.png)
 
many thanks

**Comment by miked131** [comment]
thankyou @LucasAlegre!

**Comment by miked131** [comment]
Hi @LucasAlegre, just to reopen this issue, I've only just noticed in the parallel_env that the 4 system metrics are not being attached to the infos return, even with the 'add_system_info=True' flag added to the env. They do get added to the csv outputs though.
many thanks!

**Comment by LucasAlegre** [comment]
Hi @miked131, just fixed this in 13102e216634b3e7dba8fe0b95b96a0863c98e7b

However, the system info is duplicated at the info of each agent, because the petting zoo API does not allow a key that is not an agent id.

**Comment by miked131** [comment]
thanks @LucasAlegre that works for me
