### ISSUE TITLE
Use sumo-rl on Windows

### ISSUE THREAD

**Issue by Sliver98** [LucasAlegre/sumo-rl#144]
Thanks the authors' contribution for RL! I'm new in learning this field, but I'm interested in sumo-rl very much! 
I wanna ask that can I use sumo-rl on my Windows PC? I have tried to install it on my PC, but I failed. So I must install and use it on Linux ? Looking forwrad to your reply.

**Comment by LucasAlegre** [comment]
I never tried running it on Windows, but I suppose it should also work, as you can install SUMO on Windows too. I recommend using it on Linux anyway.

**Comment by Sliver98** [comment]
Thanks very much for your rocommendation!
