### ISSUE TITLE
Issue with ql_4x4grid

### ISSUE THREAD

**Issue by simsimiSION** [LucasAlegre/sumo-rl#15]
Hi. When I test your experiment, I get something problem.
When I running the code with this environment, I get 
```    
return self.radix_encode([phase, elapsed] + density_queue)
  File "/home/simsimi/桌面/sumo-rl-master/sumo_rl/environment/env.py", line 286, in radix_encode
    res = res * self.radix_factors[i] + values[i]
IndexError: list index out of range
```
Could you help me to solve this problem? Thanks.

**Comment by LucasAlegre** [comment]
Hi,

I solved this problems in my last commit: fb5c57b0664b8bf5d5673d84acb4dcc9c7a947e7

Cheers,
Lucas
