### ISSUE TITLE
Some questions of  hierarchical reinforcement learning to sumo_rl.

### ISSUE THREAD

**Issue by locker2153** [LucasAlegre/sumo-rl#156]
I tried to configure a top-level agent for multi-agent , but I found that in the sumoenvironment, it seems impossible to change the observation and actions for  a top-level agent. In the rllib library, the pettingzoo environment seems to only support all agents using the same observation and action.
In order to solve this problem I have used 'supeisuit' trying to modify the top agent of obs as well as the actions. It is a pity that did not work. Multi-agent environment has not been identified as a Parallelenv
Do you have any good ideas ? plz

**Comment by LucasAlegre** [comment]
I suggest you ask the PettingZoo developers for help. You can find them in the corresponding channel in the FaramaFoundation discord: https://discord.com/invite/PfR7a79FpQ

**Comment by locker2153** [comment]
> I suggest you ask the PettingZoo developers for help. You can find them in the corresponding channel in the FaramaFoundation discord: https://discord.com/invite/PfR7a79FpQ

3Q ，i will try
