### ISSUE TITLE
Making the traffic In Sync

### ISSUE THREAD

**Issue by giriseena** [LucasAlegre/sumo-rl#16]
Thanks for the wonderful project, 

Tried A2C Trainer for the Traffic Simulation for reducing the waiting time, any suggestion if we need maintain the adjoining junction "In Sync"

**Comment by LucasAlegre** [comment]
Hi,

Thank you!
Currently, there is not an explicit way of doing this. However, the traffic signal agents should learn to do so in case syncing improves the cumulative reward. 
I would recommend looking for RL algorithms with coordination mechanisms.

Cheers
