### ISSUE TITLE
Lane identifiers corresponding to observations

### ISSUE THREAD

**Issue by miked131** [LucasAlegre/sumo-rl#162]
Hi @LucasAlegre I was wondering if its possible to see which elements of observations correspond to which lanes? for example, using Resco Cologne3, TLS 360086 returns an observation space of size 17. Assuming the first two elements are 'phase_one_hot' and 'min_green' I'd like to be able to identify which elements of the rest of the array correspond to certain lanes.

I'm also a little confused by observation type in this particular example....with the remaining 15 observations being a 'lane_n_density' and 'lane_n_queue' for each lane, I would have thought it would be an even number of observations....hoping could you explain it for me?

many thanks.

**Comment by LucasAlegre** [comment]
Hi @miked131,

'phase_one_hot' has the dimension of the number of green phases, so 2 in this case. 
You can check the order that the lanes are considered in the attribute 'lanes' at https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/traffic_signal.py#L97

**Comment by miked131** [comment]
thankyou @LucasAlegre
