### ISSUE TITLE
Connection closed by SUMO

### ISSUE THREAD

**Issue by way-thu** [LucasAlegre/sumo-rl#167]
Hello, I meet the problem when i run dqn_big_intersection.py in experiments folder, the error occurs like below, could u help me to solve this？ thanks
![image](https://github.com/LucasAlegre/sumo-rl/assets/113359869/537d16a7-6389-48c5-91ff-16ba75117deb)

**Comment by 88daoer** [comment]
Hello, I encountered the same issue. May I ask how you eventually resolved it?
