### ISSUE TITLE
Consistently returns some information when running in Linux

### ISSUE THREAD

**Issue by Aegis1863** [LucasAlegre/sumo-rl#168]
Thank you very much for building sumo-rl, it helps me a lot to conduct RL experiments here. 

Recently I built a training in jupyter locally on windows. When I run it, there is nothing except the progress bar, it's neat and clean, so everything works fine on Windows. 

But when I run the code on the server in Linux, it keeps returning me some information, like in the later picture, which seems to be what traci is returning (I'm not sure), and as the training increases, this information gets more and more, you know that a large number of returns will cause memory usage, nevertheless, such training can still be completed. 

But I want to eliminate such output, do you have any suggestions, I am not sure at the moment if this is a problem of `sumo-rl` or `sumo` question itself. If you have any suggestions, I'd be very grateful.

![image](https://github.com/LucasAlegre/sumo-rl/assets/46989391/d6ef70a4-e7b1-4ae4-abf2-bc95c4f8c8f1)

**Comment by LucasAlegre** [comment]
Hi!

Try to set `sumo_warnings` to False. See https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/env.py#L70

**Comment by LucasAlegre** [comment]
@Aegis1863 did that solve your issue?

**Comment by Aegis1863** [comment]
> @Aegis1863 did that solve your issue?

Hi! I tried these days, I specified this parameter as false, but didn't work, it will still constantly give feedback, but also, it will not happen in windows .

But it didn't cause big problems so i just let it go. XD

**Comment by Aegis1863** [comment]
This issue is mainly due to output rendering, which should have been refreshed repeatedly on the same line, but this is not possible in some terminals, so the new information does not overwrite the original information, resulting in overlays.

**Comment by Aegis1863** [comment]
solved it by adding a parameter when make envrionment: `additional_sumo_cmd='--no-step-log'`
like:
```
env = gym.make('sumo-rl-v0',
                        net_file=args.net,
                        route_file=args.flow,
                        additional_sumo_cmd='--no-step-log',  # HERE
                        )
```
