### ISSUE TITLE
Statistics regarding emergency braking and collisions

### ISSUE THREAD

**Issue by rohitrajgopalan** [LucasAlegre/sumo-rl#169]
Hi Lucas, 

I have been training my MARL algorithms using the SUMO environments, and I have observed during training, validation and testing that vehicles had either performed emergency braking or were in collisions based on the printed WARNING messages.

Is there a way to record these kinds of statistics as well?

**Comment by LucasAlegre** [comment]
Hi, this is not implemented in sumo-rl at the moment, but could be easily added using getCollision https://sumo.dlr.de/docs/TraCI/Simulation_Value_Retrieval.html. If you want, you can submit a PR.
