### ISSUE TITLE
sth wrong when running ppo_4x4grid.py

### ISSUE THREAD

**Issue by 1486402863** [LucasAlegre/sumo-rl#171]
F:\Anaconda\lib\site-packages\gymnasium\utils\passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
F:\Anaconda\lib\site-packages\gymnasium\utils\passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")

How to solve this?

**Comment by LucasAlegre** [comment]
Can you share the script that originated this error? Also, make sure you have recent versions of gymnasium and pettingzoo libraries.

**Comment by 1486402863** [comment]
the version of my gymnasium is 0.29.1
the version of my pettingzoo is 1.24.2
The script I used is in the attachment.

[ppo_4x4grid.zip](https://github.com/LucasAlegre/sumo-rl/files/13759090/ppo_4x4grid.zip)

**Comment by LucasAlegre** [comment]
Fixed in https://github.com/LucasAlegre/sumo-rl/commit/973f1699f8bb8b16216dd3ead8b444593e5484bb
