### ISSUE TITLE
Trouble with Action Space description

### ISSUE THREAD

**Issue by prajwalvinod** [LucasAlegre/sumo-rl#175]
While running the python environment with my SUMO network I encounter the following error when I run the code:

```
  Traceback (most recent call last):
    File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\pydevd.py", line 1500, in _exec
      pydev_imports.execfile(file, globals, locals)  # execute the script
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\JetBrains\PyCharm 2023.2.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
      exec(compile(contents+"\n", file, 'exec'), glob, loc)
    File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\env_trial.py", line 624, in <module>
      next_obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\env_trial.py", line 310, in step
      self._apply_actions(action)
    File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\env_trial.py", line 343, in _apply_actions
      self.traffic_signals[self.ts_ids[0]].set_next_phase(actions)
    File "C:\Users\prajw\PythonFiles\Thesis\RL_for_Freeway\Hegyi_Model\tls_v3.py", line 166, in set_next_phase
      self.sumo.trafficlight.setRedYellowGreenState(self.id, self.all_phases[self.green_phase].state)
                                                             ^^^^^^^^^^^^^^^
  AttributeError: 'TrafficSignal' object has no attribute 'all_phases'
  
  Process finished with exit code 1
```

In my network there is only one traffic light at the on ramp of a freeway. I will attach the necessary files with this. 
1. I was wondering what is causing this issue and how to solve it ?
2. Also while running the test there seems to be no output file being generated.

Thanks in advance.
[net.zip](https://github.com/LucasAlegre/sumo-rl/files/13696554/net.zip)

**Comment by LucasAlegre** [comment]
Hi @prajwalvinod.

Your traffic signal has only one green phase:
<tlLogic id="J8" type="static" programID="0" offset="0">
        <phase duration="31" state="r"/>
        <phase duration="4"  state="y"/>
        <phase duration="20" state="g"/>
</tlLogic>

This can not work because the agent has only one possible action.

**Comment by prajwalvinod** [comment]
Hi @LucasAlegre,

Thanks for your reply. 

1. Does that mean I have to modify the phases in such a way that I have more green phases even though I have only 1 traffic light to control ? 
2. Conversely, is there a way to modify the environment or the classes in a way that this can be overlooked ?

Thanks.

**Comment by prajwalvinod** [comment]
> Hi @LucasAlegre,
> 
> Thanks for your reply.
> 
> 1. Does that mean I have to modify the phases in such a way that I have more green phases even though I have only 1 traffic light to control ?
> 2. Conversely, is there a way to modify the environment or the classes in a way that this can be overlooked ?
> 
> Thanks.

Hey @LucasAlegre,

By any chance have you seen these queries ?

Regards

Prajwal

**Comment by LucasAlegre** [comment]
Hi @prajwalvinod,

It is not that you need more than one traffic light. The problem is that your traffic light has only one green phase. That is, it only controls whether the cars can move or not. This does not make sense, as there is no reason for it to ever go red.

sumo-rl expects it to be something like:

```
<tlLogic id="J8" type="static" programID="0" offset="0">
        <phase duration="31" state="rg"/>
        <phase duration="4"  state="yy"/>
        <phase duration="2" state="rr"/>
       <phase duration="31" state="gr"/>
        <phase duration="4"  state="yy"/>
        <phase duration="2" state="rr"/>
</tlLogic>
```

Then the agent can choose between "gr" and "rg".

**Comment by prajwalvinod** [comment]
Hey @LucasAlegre,

Thank you so much for clearing this confusion. It has helped a lot and simplified my debugging.

Regards

Prajwal
