### ISSUE TITLE
any implement for car following?

### ISSUE THREAD

**Issue by laoyouf** [LucasAlegre/sumo-rl#178]
Hi, Lucas. Nice work! I would like to ask if your sumo-rl library can implement multi-agent vehicle control? For example, I am trying to make a scene: 1km straight single-lane for car following . There are two kinds of vehicles on the road, one is controlled by IDM and the other is controlled by DDPG algorithm. How can I use your environment to implement such an example?

**Comment by LucasAlegre** [comment]
Hi, sumo-rl is a library for traffic signal control only. The problem of car following is completely different and would require implementing a new type of environment. You can probably reuse a lot of sumo-rl code for implementing that, but it is not straightforward.

**Comment by laoyouf** [comment]
ok, I will find other libraby for this. I would really appreciate it if you know of any other RL env libraries for car following models, please let me know.
