### ISSUE TITLE
How to save and reload the environment?

### ISSUE THREAD

**Issue by raphaelstraub** [LucasAlegre/sumo-rl#188]
I need to perform an exploration where i have to save and reload the environment. Is this possible? I found nothing in the documentation of this library and PettingZoo.

Thank you!

**Comment by LucasAlegre** [comment]
Do you mean saving the environment in the middle of the simulation? I think this is not possible in SUMO. However, you can always instantiate the same environment by passing the same arguments to the constructor.

**Comment by raphaelstraub** [comment]
Thank you! I had hoped, that there might be a better approach. Currently I am doing this like you proposed: Using the same seed and then just repeat all the actions
