### ISSUE TITLE
issues about the reward

### ISSUE THREAD

**Issue by way-thu** [LucasAlegre/sumo-rl#189]
hello Lucas, thanks for your sharing, there is one thing I feel confused, is your simulation set for a fixed total time and the simulation stops when the time reaches the total time?

**Comment by LucasAlegre** [comment]
Yes, the simulation runs for a fixed number of simulated seconds in sumo: https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/env.py#L55C9-L55C21. See the documentation: https://lucasalegre.github.io/sumo-rl/documentation/sumo_env/
