### ISSUE TITLE
running error on ppo_4x4grid.py

### ISSUE THREAD

**Issue by FanFan2021** [LucasAlegre/sumo-rl#190]
![Screenshot 2024-03-08 at 9 58 28 PM](https://github.com/LucasAlegre/sumo-rl/assets/82756357/06828291-ea82-498c-9a06-5f65dbcd2134)

I directly run ppo_4x4grid.py, it turn out that the episode_reward_mean and episode_len_mena are NAN. I am quite confused~

**Comment by LucasAlegre** [comment]
This means that the episode has not yet finished. The episode is that experiment is quite long, see total number of time steps.

**Comment by FanFan2021** [comment]
I see, thank you so much!
