### ISSUE TITLE
change the action to switch to different signal timing schemes

### ISSUE THREAD

**Issue by littlelittlehui** [LucasAlegre/sumo-rl#194]
Hello, I ran the code for the two-lane intersection，I'm not very familiar with sumo，Can you help me answer some questions， if I want to change the action to switch to different signal timing schemes on the basis of the current code, how should I modify it, can you provide some suggestions?if I want to change the action to switch to different signal timing schemes on the basis of the current code, how should I modify it, can you provide some suggestions?

**Comment by LucasAlegre** [comment]
The actions in sumo-rl are the next green-phase to be active. Currently, there is no way to make the actions completely different signal timing schemes. To implement this, you would have to significantly change the logic of environment and traffic signal classes.
