### ISSUE TITLE
Why delta_time should be greater than yellow time?

### ISSUE THREAD

**Issue by jackli100** [LucasAlegre/sumo-rl#196]
Excuse me, I found if the delta_time is less than yellow time, there will be an error raised in env.py. What are the reasons for this?

**Comment by LucasAlegre** [comment]
The delta_time is the number of seconds between consecutive actions of the agents. When an agent selects a new green phase, it will first set the phase to yellow for yellow_time seconds. If delta_time < yellow_time, the agent would be able to change another phase before the previous actions was actually executed.

**Comment by jackli100** [comment]
` def set_next_phase(self, new_phase: int):
        """Sets what will be the next green phase and sets yellow phase if the next phase is different than the current.

        Args:
            new_phase (int): Number between [0 ... num_green_phases]
        """
        new_phase = int(new_phase)
        if self.green_phase == new_phase or self.time_since_last_phase_change < self.yellow_time + self.min_green:
            # self.sumo.trafficlight.setPhase(self.id, self.green_phase)
            self.sumo.trafficlight.setRedYellowGreenState(self.id, self.all_phases[self.green_phase].state)
            self.next_action_time = self.env.sim_step + self.delta_time
        else:
            # self.sumo.trafficlight.setPhase(self.id, self.yellow_dict[(self.green_phase, new_phase)])  # turns yellow
            self.sumo.trafficlight.setRedYellowGreenState(
                self.id, self.all_phases[self.yellow_dict[(self.green_phase, new_phase)]].state
            )
            self.green_phase = new_phase
            self.next_action_time = self.env.sim_step + self.delta_time
            self.is_yellow = True
            self.time_since_last_phase_change = 0`
         In this function(in trafficsignal.py) you have already made a judgement on whether the current situation has lasted the yellow and minimum green time, I'm wondering if that assertion statement in env,py is duplicated and can be removed?

**Comment by LucasAlegre** [comment]
No, the assertion on env.py is not duplicated, and is required to alert the user since the logic in the function above only works when delta_time > yellow_time.

**Comment by jackli100** [comment]
Hello! I've identified why the assert statement can't be disabled by carefully reviewing the code. The issue is during the yellow light phase: even though the system does not assign a new phase, it reverts back to the original green light phase. 

But here's the problem:

This setup restricts the ability to make decisions at certain times when it would otherwise be possible. Let's assume the yellow light lasts 2 seconds, the green light 5 seconds, and the minimum decision-making window is 3 seconds. If a decision is made at second 0, neither second 3 nor second 6 are viable for making another decision. In fact, a decision could be made at second 8, but we must wait until second 9.

This means that essentially the actual minimal viable times for the green light are really only at 3, 6, 9 seconds and so on.(if yellow_time = 2)

**Comment by LucasAlegre** [comment]
This was defined this way so that each call to step() is separated by exactly `delta_time` seconds. This is important because each action executed in the MDP should last the same amount of time. If the minimal green time is a not a multiple of delta_time, then the agent will make decisions at irregular time steps.
