### ISSUE TITLE
RESCO benchmark has no cars

### ISSUE THREAD

**Issue by MelihDarcanxyz** [LucasAlegre/sumo-rl#199]
Some of the RESCO benchmark files doesn't spawn any cars, or if they do, cars follow some specific routes always.

## arterial4x4
As you can see, cars follow some specific routes and spawn from the same locations always. Yellow dots are the cars. No car goes to some roads / routes. It's not about traffic lights because they are opened / closed randomly. So every direction should be allowed at some point.

![Screenshot from 2024-05-04 14-39-35](https://github.com/LucasAlegre/sumo-rl/assets/57872471/9199a50f-60e5-439f-abf4-9ad43f956e53)

## cologne{1,3,8}
No cars are spawned.

![Screenshot from 2024-05-04 14-40-46](https://github.com/LucasAlegre/sumo-rl/assets/57872471/5952c9c3-5d4e-48d4-8cd2-9ea7e228be0a)
![Screenshot from 2024-05-04 14-41-35](https://github.com/LucasAlegre/sumo-rl/assets/57872471/a9207dd0-1983-4ce4-80b6-fbc6bccebae5)
![image](https://github.com/LucasAlegre/sumo-rl/assets/57872471/3c6a4eea-3e9d-4b5f-8b15-9d3c7aee469f)

## ingolstadt{1,7,21}
No cars are spawned.

![image](https://github.com/LucasAlegre/sumo-rl/assets/57872471/b3e21de1-dae1-4c1c-8dea-f4d5592fec50)
![image](https://github.com/LucasAlegre/sumo-rl/assets/57872471/6f83e11d-6b43-4a3e-a595-07023c75a701)
![image](https://github.com/LucasAlegre/sumo-rl/assets/57872471/7ea9aa0d-06db-4b21-82df-ad385c607642)

## grid4x4
This is the only one that's working as it should. Cars follow random routes and spawns from everywhere.

![image](https://github.com/LucasAlegre/sumo-rl/assets/57872471/859b1aac-2bb7-4e69-9918-1c4e31f89db6)

**Comment by LucasAlegre** [comment]
I believe you are initializing the simulations from time steps 0, while the vehicles are only inserted later on. You have to instantiate the environments with the following:

**Comment by LucasAlegre** [comment]
I believe you are starting the simulation from time step 0, while in these networks the vehicles are inserted later on in the simulation. Check: https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/resco_envs.py

If you instantiate the environment with, for instance:
```
from sumo_rl import cologne8
env = cologne8(use_gui=True, yellow_time=2, render_mode='human')
```
Regarding the routes, they are defined in the .rou files and are the exact route files used in the RESCO benchmark paper. I don't know if they should be random/fixed, but you can check the route files to see how they are supposed to work.

Then the simulation should start at the time step where vehicles start to be inserted.

**Comment by MelihDarcanxyz** [comment]
Thanks for your reply! I didn't know it. I ran the code you provided, it outputs:

```
Error: File '~/.cache/pypoetry/virtualenvs/detraffic--pKdqVlZ-py3.10/lib/python3.10/site-packages/sumo_rl/../nets/RESCO/cologne8/cologne8.net.xml' is not accessible (No such file or directory).
Quitting (on error).
```

Then I run this command:
```prompt
user@host:detraffic$ ls ~/.cache/pypoetry/virtualenvs/detraffic--pKdqVlZ-py3.10/lib/python3.10/site-packages/sumo_rl
agents  environment  exploration  __init__.py  __pycache__  util
```

Poetry is used to install the package. But I don't think it should make any difference. `nets` is not present in `sumo_rl` installation directory or its parents / subdirectories.

**Comment by LucasAlegre** [comment]
Thanks for spotting this, I think the nets folder is indeed not in the package when installing from pip/poetry. You can git clone the library and installing it locally 'pip install -e .' . Otherwise, maybe it is more convenient to you to simply set the correct parameter of "num_seconds" used in https://github.com/LucasAlegre/sumo-rl/blob/main/sumo_rl/environment/resco_envs.py when instantiating your environment

**Comment by MelihDarcanxyz** [comment]
Of course, thanks! Is it possible to move the `nets` folder to `sumo-rl` folder in the repo? Would that break anything? If not, it may be convenient to do in this case. Also, I may have to delete the `..` part from path.

**Comment by LucasAlegre** [comment]
I have just release v1.4.5, which should include the nets folder. Could you please test if it solves your problem?

**Comment by MelihDarcanxyz** [comment]
Works without errors, and cars spawn too! Thanks a lot for your time and the project.
