### ISSUE TITLE
How can we accout for the startup delay during phase change

### ISSUE THREAD

**Issue by giriseena** [LucasAlegre/sumo-rl#20]
Hi Lucas,

We are able to optimize the network under theoretical conditions, however during the change in the phase there will be startup delay induced .

How best can we account this delay in our reward / observation

**Comment by LucasAlegre** [comment]
Hi,

I believe the current reward function already takes it into account. It subtracts the accumulated delay for the current time step and the accumulated delay when the last action was taken. So the startup delay is already included in this summation.

Cheers

**Comment by giriseena** [comment]
Thanks for the reply. 

The A2C enabled solution is performing better than vehicle actuated mode under happy condition. However when we set vehicle acceleration factor to 1m/s for example , vehicle actuated mode works better than A2C.

**Comment by LucasAlegre** [comment]
How are you using vehicle actuated mode on SUMO?

Important: you probably can improve the A2C results by tuning its parameters and changing the default ones.

**Comment by giriseena** [comment]
<tlLogic id="0" programID="my_program" offset="0" type="actuated">
  <param key="max-gap" value="3.0"/>
  <param key="detector-gap" value="2.0"/>
  <param key="passing-time" value="2.0"/>
  <param key="vTypes" value=""/>
  <param key="show-detectors" value="false"/>
  <param key="file" value="NULL"/>
  <param key="freq" value="300"/>

  <phase duration="31" minDur="5" maxDur="45" state="GGggrrrrGGggrrrr"/>
  ...
</tlLogic>


This I am using in the net file

**Comment by giriseena** [comment]
<tlLogic id="0" programID="my_program" offset="0" type="actuated">
  <param key="max-gap" value="3.0"/>
  <param key="detector-gap" value="2.0"/>
  <param key="passing-time" value="2.0"/>
  <param key="vTypes" value=""/>
  <param key="show-detectors" value="false"/>
  <param key="file" value="NULL"/>
  <param key="freq" value="300"/>

  <phase duration="31" minDur="5" maxDur="45" state="GGggrrrrGGggrrrr"/>
  ...
</tlLogic>

**Comment by giriseena** [comment]
I am using this in net file

<tlLogic id="0" programID="my_program" offset="0" type="actuated">
  <param key="max-gap" value="3.0"/>
  <param key="detector-gap" value="2.0"/>
  <param key="passing-time" value="2.0"/>
  <param key="vTypes" value=""/>
  <param key="show-detectors" value="false"/>
  <param key="file" value="NULL"/>
  <param key="freq" value="300"/>

  <phase duration="31" minDur="5" maxDur="45" state="GGggrrrrGGggrrrr"/>
  ...
</tlLogic>

**Comment by giriseena** [comment]
<tlLogic id="0" programID="my_program" offset="0" type="actuated">
  <param key="max-gap" value="3.0"/>
  <param key="detector-gap" value="2.0"/>
  <param key="passing-time" value="2.0"/>
  <param key="vTypes" value=""/>
  <param key="show-detectors" value="false"/>
  <param key="file" value="NULL"/>
  <param key="freq" value="300"/>

  <phase duration="31" minDur="5" maxDur="45" state="GGggrrrrGGggrrrr"/>
  ...
</tlLogic>

**Comment by giriseena** [comment]
![IMG_20201223_225947](https://user-images.githubusercontent.com/46781635/103022846-c6460d00-4572-11eb-9bde-32de958ddce4.jpg)

**Comment by giriseena** [comment]
I am using above type in net file
