### ISSUE TITLE
envionment checking

### ISSUE THREAD

**Issue by wkkdhj** [LucasAlegre/sumo-rl#200]
PPOConfig()
        .environment(env=env_name, disable_env_checking=False)
It seems that the environment detection does not have the built-in MultiAgentEnv check, which will affect the rllib algorithm to enable the callback function

**Comment by LucasAlegre** [comment]
To use rllib I suggest using the PettingZoo API and using the rllib function to make the env compatible: https://docs.ray.io/en/latest/rllib/rllib-env.html#pettingzoo-multi-agent-environments

**Comment by wkkdhj** [comment]
Thanks for your recommendation. I'll give it a try.
