### ISSUE TITLE
Returning image as state

### ISSUE THREAD

**Issue by deltag0** [LucasAlegre/sumo-rl#215]
Documentation states that we can create our own observation:
"You can define your own observation by implementing a class that inherits from ObservationFunction and passing it to the environment constructor."

So, would it be possible to return an image (tensor form) as the state of the environment? If so, what would I need to modify in the default observation function.

**Comment by LucasAlegre** [comment]
Yes, you would need to implement something that captures the simulation screen (see https://sumo.dlr.de/docs/TraCI/Change_GUI_State.html), and change the observation_space accordingly too.
