### ISSUE TITLE
Run Simulation for more time

### ISSUE THREAD

**Issue by deltag0** [LucasAlegre/sumo-rl#217]
I've been trying to find a way to train the model for longer because after a certain amount of steps, there are no more vehicles in the environment. Which parameter do I need to change to achieve this? 

Nothing I've tried has worked, and looking through the `SumoEnvironment`, I didn't figure out what I could change.

**Comment by LucasAlegre** [comment]
You have to modify the .rou,xml files and chage the duration of the traffic flow. See https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html

**Comment by deltag0** [comment]
Thank you!
