### ISSUE TITLE
Error on ppo_4x4grid.py

### ISSUE THREAD

**Issue by YTLYNN** [LucasAlegre/sumo-rl#218]
![image](https://github.com/user-attachments/assets/4c9b209b-ec97-4224-b6a2-b4e72d2886b8)

Hi Lucas, I attempted to run the multi-agent example ppo_4x4grid.py, but encountered an error that I suspect is related to the RLlib version. Could you suggest which RLlib version might work best for this example? Additionally, are there other multi-agent examples available that use SB3? I'm currently working on implementing MARL algorithms for custom SUMO networks but am facing challenges right from the start. Your advice would be greatly appreciated!

**Comment by LucasAlegre** [comment]
Hi @YTLYNN , sumo-rl is compatible with the latest version of petting-zoo. So to run rllib or any other library, just follow the guides on how to train RL algorithm with any pettingzoo environment.

**Comment by YTLYNN** [comment]
I will try that, thank you for pointing out!

**Comment by LucasAlegre** [comment]
@YTLYNN Try the versions in the script introduced in https://github.com/LucasAlegre/sumo-rl/commit/973f1699f8bb8b16216dd3ead8b444593e5484bb
