### ISSUE TITLE
How to get the waiting time & queue length by edges at every junction

### ISSUE THREAD

**Issue by amerfathullah** [LucasAlegre/sumo-rl#25]
Hi Lucas,

I created a road network and routes, and trained my network using sumo-rl. The output csv file from your code only gives the output of total waiting time and total vehicles stopped at each time step. However, I want to get the waiting time & queue length by edges at every junction during each time step, just like when using "--queue-output" command line from SUMO. Do I have to modify your env.py to make this happen or is there any better alternatives?

Regards,
Amer

**Comment by amerfathullah** [comment]
I figured it would be best to save the model after the training and compare the results of --queue-output before & after training. The question is, how to save the model?

**Comment by LucasAlegre** [comment]
Hi,

You can get the waiting time & queue lengths by modifying the method below to also record the metrics per traffic signal or per lane.

def _compute_step_info(self):
        return {
            'step_time': self.sim_step,
            'reward': self.traffic_signals[self.ts_ids[0]].last_reward,
            'total_stopped': sum(self.traffic_signals[ts].get_total_queued() for ts in self.ts_ids),
            'total_wait_time': sum(sum(self.traffic_signals[ts].get_waiting_time_per_lane()) for ts in self.ts_ids)
        }

**Comment by LucasAlegre** [comment]
> I figured it would be best to save the model after the training and compare the results of --queue-output before & after training. The question is, how to save the model?

It depends on the algorithm you are using. You then could check the documentation of the RL library you are using (stable-baselines, rllib, etc).

**Comment by amerfathullah** [comment]
alright, thanks for the replies. I'll check the documentation later
