### ISSUE TITLE
Error while running any of the experiments

### ISSUE THREAD

**Issue by vishruth-v** [LucasAlegre/sumo-rl#28]
I faced this issue while running any of the python executables in the experiments folder

Traceback (most recent call last):
  File "a3c_4x4grid.py", line 16, in <module>
    from sumo_rl import SumoEnvironment
  File "/Users/vish/College/Semester 4/Mini Project/env/lib/python3.8/site-packages/sumo_rl/__init__.py", line 1, in <module>
    from sumo_rl.environment.env import SumoEnvironment
ModuleNotFoundError: No module named 'sumo_rl.environment'

**Comment by LucasAlegre** [comment]
Hi,

You need to install the package, as described in the README. So you can import the environment class.

**Comment by vishruth-v** [comment]
Hi Lucas, 
I had installed the stable release of the package i.e pip install sumo-rl in a venv, when I faced the issue, and I still do face the same issue with the stable release version.
But installing the unreleased version by cloning and using pip install -e . seemed to work with no issues (pip install -e . was also done while a venv was activate).

**Comment by LucasAlegre** [comment]
Thanks for the feedback! I will fix the stable release of the package!

**Comment by yuy01** [comment]
thanks, i have also met the problem, and solve it by run "pip install -e . "
