### ISSUE TITLE
a single-agent

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [LucasAlegre/sumo-rl#29]
Thanks to the contribution of the author, this open source code is a great contribution to the community. Is there an example of running a single-agent using RLlib?

**Comment by LucasAlegre** [comment]
Thank you!
You can just follow the examples in the "experiments" folder. A single-agent environment should run in RLlib the same way :)

**Comment by Yuanzhuo-Liu** [comment]
OK, Thanks!  When I run this file "dqn_2way-single-intersection.py", happened some erros(Download from your library, nothing changed):
/home/meta/anaconda3/envs/ray/bin/python3.8 /home/meta/PycharmProjects/paper-1/sumo-rl/experiments/dqn_2way-single-intersection.py
Traceback (most recent call last):
  File "/home/meta/PycharmProjects/paper-1/sumo-rl/experiments/dqn_2way-single-intersection.py", line 18, in <module>
    env = SumoEnvironment(net_file='nets/2way-single-intersection/single-intersection.net.xml', route_file='nets/2way-single-intersection/single-intersection-vhvh.rou.xml', out_csv_name='outputs/2way-single-intersection/dqn', single_agent=True, use_gui=False, num_seconds=100000, max_depart_delay=0)
TypeError: SumoEnvironment() takes no arguments

How can I solve it? Thanks!
