### ISSUE TITLE
missing params in save_csv() 

### ISSUE THREAD

**Issue by Exorcismus** [LucasAlegre/sumo-rl#3]
python3 experiments/ql_single-intersection.py 
 Retrying in 1 seconds
 Retrying in 1 seconds?UPS, TraCI: 2ms, vehicles TOT 0 ACT 0 BUF 0)           
Step #20000.00 (0ms ?*RT. ?UPS, Traceback (most recent call last): 42 BUF 0)  
  File "experiments/ql_single-intersection.py", line 89, in <module>
    env.save_csv()

> TypeError: save_csv() missing 2 required positional arguments: 'out_csv_name' and 'run'

Step #20005.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownBUF 0)  
Quitting (on error).

the function definition is

```
    def save_csv(self, out_csv_name, run):
        if out_csv_name is not None:
            df = pd.DataFrame(self.metrics)
            df.to_csv(out_csv_name + '_run{}'.format(run) + '.csv', index=False)
```

and it's being called as only`  save_csv()` with no arguments

**Comment by LucasAlegre** [comment]
I forgot to update the experiments after updating the code do SUMO v1.1.0.
My last commit fixed it,
Thanks!
