### ISSUE TITLE
Error in plotting time delay vs iterations graph

### ISSUE THREAD

**Issue by SaiAakash** [LucasAlegre/sumo-rl#30]
I am able to run the ql_single-intersection.py completely without any error. While running the plot.py in the outputs folder the following error occurs. It shows a KeyError for the total_wating_time column generated as a result of running the ql_single-intersection.py
![Screenshot from 2021-04-10 18-57-02](https://user-images.githubusercontent.com/64794820/114271352-8d9d4700-9a2e-11eb-9ad1-cefb41b2f0fc.png)

**Comment by LucasAlegre** [comment]
Hi,

The problem is the whitespaces in the filename when calling the script in the terminal. Whitespaces should be proceeded by '\'.
Or you can just rename the output file and remove the whitespace :)

**Comment by SaiAakash** [comment]
Renaming the output file removing the whitespaces doesn't give any effect. It results in the same KeyError: 'total_wait_time'

**Comment by SaiAakash** [comment]
Can you suggest any other method to resolve this issue ?

**Comment by LucasAlegre** [comment]
Hi, can you send me the output file that is resulting in error?

**Comment by SaiAakash** [comment]
I have attached the output file resulting in error below.
[2021-04-1620:09:34_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv](https://github.com/LucasAlegre/sumo-rl/files/6331394/2021-04-1620.09.34_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv)

**Comment by LucasAlegre** [comment]
Hi,

I have ran the command:

`python outputs/plot.py -f ~/Downloads/2021-04-1620.09.34_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv `

and it worked fine. Please check whether you are using the correct filename.

**Comment by Yuanzhuo-Liu** [comment]
I had the same problem when I ran other files , ‘’KeyError: 'total_wait_time'‘’
