### ISSUE TITLE
Blank csv output with fixed lights

### ISSUE THREAD

**Issue by RainbowLampp** [LucasAlegre/sumo-rl#32]
Hi!

We tried running your 'ql_2way-single-intersection.py' experiment, but when we tried setting fixed to true it runs, but the output is blank.

How do we get the output of the fixed lights? We want to use it to compare with trained model

**Comment by LucasAlegre** [comment]
Hello,

Sorry for the late reply.
I have fixed this in the last commit just now :)

Cheers!
