### ISSUE TITLE
a single agent 

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [LucasAlegre/sumo-rl#33]

**Comment by Yuanzhuo-Liu** [comment]
Hi!
Could you help to train the"2way-single-intersection" using rllib.dqn（rainbow）. I am following your "A3C_4x4grid" way of training, but I get the following error, if it is because the environment is not Mutilagent？

**Comment by Yuanzhuo-Liu** [comment]
![sendpix1](https://user-images.githubusercontent.com/68255669/115542582-689aa680-a26e-11eb-8c4c-255772f89fe3.jpg)
![sendpix2](https://user-images.githubusercontent.com/68255669/115542736-9384fa80-a26e-11eb-951e-1eb6c4a6b0ba.jpg)

**Comment by LucasAlegre** [comment]
The problem is that you are using a single-agent version of the environment. Hence, last_obs is not a dictionary and then it gives you the error "numpy.ndarray object has no attribute keys".

**Comment by zzchuman** [comment]
> Hi!
> Could you help to train the"2way-single-intersection" using rllib.dqn（rainbow）. I am following your "A3C_4x4grid" way of training, but I get the following error, if it is because the environment is not Mutilagent？

你好，可以一起讨论一下这个代码吗？
