### ISSUE TITLE
Saving output for ql_4x4grid.py

### ISSUE THREAD

**Issue by Shanki5** [LucasAlegre/sumo-rl#34]
I tried to add a line 
`env.save_csv(out_csv, run)`

to the python file for 4x4 grids but am getting the following error
`shankrith@Aurelius:~/Traffic_Constable/sumo-rl$ python3 experiments/ql_4x4grid.py 
  File "experiments/ql_4x4grid.py", line 49
    env.save_csv(out_csv, run)
                             ^
TabError: inconsistent use of tabs and spaces in indentation
`

Will the env_save command work for 4x4 grids?

**Comment by LucasAlegre** [comment]
You added a line using tab. In Python we usually add 4 spaces for indentation (or configure the editor so that a TAB adds four spaces). This a python parser error, not an error with SUMO-RL.
