### ISSUE TITLE
What is the environment configure, such as tensorflow version and so on?

### ISSUE THREAD

**Issue by yuy01** [LucasAlegre/sumo-rl#36]

**Comment by LucasAlegre** [comment]
Hi!

You can check this on setup.py file. 
But basically this repository should work with the latest versions of numpy, pandas, gym and rlllib.

Cheers

**Comment by yuy01** [comment]
what about tensorflow version?

**Comment by LucasAlegre** [comment]
SUMO-RL does not have a direct dependency on tensorflow.  You only need tensorflow to run your favorite external RL lib (rllib, stable-baselines, etc.)
