### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/single-intersection/2021-05-06 12:36:47_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv  ________ and_______warning:       'non-resource variables are not supported in the long term,

### ISSUE THREAD

**Issue by yuy01** [LucasAlegre/sumo-rl#37]
when ran python3 experiments/ql_single-intersection.py, i met an error:

/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
 Retrying in 1 seconds
/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 5ms, vehicles TOT 0 ACT 0 BUF 0)                      
 Retrying in 1 seconds
Step #99000.00 (0ms ?*Traceback (most recent call last): 67691 ACT 29 BUF 0)              
  File "experiments/ql_single-intersection.py", line 72, in <module>
    env.save_csv(out_csv, run)
  File "/home/project/traffic_rl/sumo-rl-master/sumo_rl/environment/env.py", line 188, in save_csv
    df.to_csv(out_csv_name + '_run{}'.format(run) + '.csv', index=False)
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/program/anaconda3/envs/tf114/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/single-intersection/2021-05-06 12:36:47_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv'
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownT 68472 ACT 30 BUF 0)             
Quitting (on error).

**Comment by LucasAlegre** [comment]
Hi,

You need to create the folder "outputs/single-intersection" in order to save a file in it.

Cheers
