### ISSUE TITLE
ileNotFoundError: [Errno 2] No such file or directory: 'outputs/single-intersection/2021-05-28 05:29:41_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv'

### ISSUE THREAD

**Issue by kriver91** [LucasAlegre/sumo-rl#39]
Hello, I am trying to test your code but I have an error while running 'ql_single-intersection.py ':

Traceback (most recent call last):
  File "experiments/ql_single-intersection.py", line 72, in <module>
    env.save_csv(out_csv, run)
  File "/home/kriver91/sumo-rl/sumo_rl/environment/env.py", line 188, in save_csv
    df.to_csv(out_csv_name + '_run{}'.format(run) + '.csv', index=False)
  File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/core/generic.py", line 3387, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 228, in save
    with get_handle(
  File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/single-intersection/2021-05-28 05:29:41_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv'
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownT 68072 ACT 26 BUF 0)             
Quitting (on error).

It seems like the code are not generating the output csv file.

**Comment by LucasAlegre** [comment]
You have to create the directory "single-intersection" first.

**Comment by TrinhTuanHung2021** [comment]
OSError: [Errno 22] Invalid argument: 'outputs/2way-single-intersection/2022-01-07 10:33:49_alpha0.1_gamma0.99_eps0.05_decay1.0_rewardwait_conn0_run1.csv'      
Step #1005.00 (1ms ~= 1000.00*RT, ~72000.00UPS, TraCI: 42ms, vehicles TOT 662 ACT 72 BUF 3

When I run this file, the program starts but the result file is not found

**Comment by dingshansun** [comment]
> Hello, I am trying to test your code but I have an error while running 'ql_single-intersection.py ':
> 
> Traceback (most recent call last): File "experiments/ql_single-intersection.py", line 72, in env.save_csv(out_csv, run) File "/home/kriver91/sumo-rl/sumo_rl/environment/env.py", line 188, in save_csv df.to_csv(out_csv_name + '_run{}'.format(run) + '.csv', index=False) File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/core/generic.py", line 3387, in to_csv return DataFrameRenderer(formatter).to_csv( File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1083, in to_csv csv_formatter.save() File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 228, in save with get_handle( File "/home/kriver91/anaconda3/envs/sumo_rl/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle handle = open( FileNotFoundError: [Errno 2] No such file or directory: 'outputs/single-intersection/2021-05-28 05:29:41_alpha0.1_gamma0.99_eps0.05_decay1.0_run1.csv' Error: tcpip::Socket::recvAndCheck @ recv: peer shutdownT 68072 ACT 26 BUF 0) Quitting (on error).
> 
> It seems like the code are not generating the output csv file.

Hi, I also had this problem.
For me, it can be solved by removing the date information in the file name.
