### ISSUE TITLE
Multi agent seting

### ISSUE THREAD

**Issue by zzchuman** [LucasAlegre/sumo-rl#40]
Hello, Lucas. I have read your code about a3c_4x4.py. Now, I have a question, you have set only one policy about policy 0. 

Is there 16 agent use the same one policy? Right?

How do the ray multi agent map the taffic light id？ Can you teach me? THANK YOU

**Comment by LucasAlegre** [comment]
If you need a different policy for each intersection, then you need to declare multiple policies in the "policies" field and define the policy mapping.
For details, you need to check Rllib documentation: https://docs.ray.io/en/master/rllib-examples.html

**Comment by zzchuman** [comment]
> 如果每个交集需要不同的策略，则需要在“policies”字段中声明多个策略并定义策略映射。
> 具体需要查看Rllib文档：[https](https://docs.ray.io/en/master/rllib-examples.html) ://docs.ray.io/en/master/rllib-examples.html[](https://docs.ray.io/en/master/rllib-examples.html)

Okay, I will go to look it. And I can not know ray multi agent id map the taffic light id? Can you teach me?
