### ISSUE TITLE
TraCIException: Connection '0' is already active

### ISSUE THREAD

**Issue by thinker310** [LucasAlegre/sumo-rl#48]
Hello, I encounter a problem with the dqn_two_way_single_intersection.py file. When it run to the last second, the error happens, as the picture below.
![image](https://user-images.githubusercontent.com/62609436/136527565-78aa123f-6f90-43f3-821b-f1217ee5be4d.png)
Could you help me please? Thank you in advance!

**Comment by thinker310** [comment]
OK, I will have a try. Thank you!

**Comment by LucasAlegre** [comment]
> OK, I will have a try. Thank you!

Let me know if it works!
