### ISSUE TITLE
How to evaluate the outcomes?

### ISSUE THREAD

**Issue by thinker310** [LucasAlegre/sumo-rl#49]
To avoid the error made by traci when training, I used libsumo and it is ok. But after it was trained, I want to evaluate the outcome and watch the viusalization with sumo-gui. So I save the model in the dqn-2way-single-intersection.py and create another py file, and import evaluate_policy from SB3 and use traci to run it. But the same problem as my last question (TraCIException: Connection '0' is already active) happened again. Therefore, I want to how to sovle it and the evaluate code is displayed as below. Thank you very much!
![image](https://user-images.githubusercontent.com/62609436/136573150-0da91f51-08e4-48d0-8a2c-22fcd7145ae4.png)
![image](https://user-images.githubusercontent.com/62609436/136573380-4b18f0b5-a159-4df2-ad87-2a475ba32bba.png)

**Comment by TrinhTuanHung2021** [comment]
> To avoid the error made by traci when training, I used libsumo and it is ok. But after it was trained, I want to evaluate the outcome and watch the viusalization with sumo-gui. So I save the model in the dqn-2way-single-intersection.py and create another py file, and import evaluate_policy from SB3 and use traci to run it. But the same problem as my last question (TraCIException: Connection '0' is already active) happened again. Therefore, I want to how to sovle it and the evaluate code is displayed as below. Thank you very much! ![image](https://user-images.githubusercontent.com/62609436/136573150-0da91f51-08e4-48d0-8a2c-22fcd7145ae4.png) ![image](https://user-images.githubusercontent.com/62609436/136573380-4b18f0b5-a159-4df2-ad87-2a475ba32bba.png)

Hello. Did you fix it? I try to evaluate the trained model but I had errors when build it
