### ISSUE TITLE
Problem with sumo-gui 

### ISSUE THREAD

**Issue by jungminx** [LucasAlegre/sumo-rl#53]
Hello I'm interested in your study and researching related studies. 
So when I tried to run with  'use_gui = True ' , then the error message came out.
'UserWarning: Could not connect to TraCI sever using port xxxxx...' 
I'm not sure where is the problem maybe I have not enough information about SUMO.

Can you help me with this problem?

**Comment by LucasAlegre** [comment]
Hi,

I need more information to understand the problem. Can you give more details?
