### ISSUE TITLE
'traci.exceptions.FatalTraCIError: connection closed by SUMO' and 'cologne8.net.xml' is not accessible'

### ISSUE THREAD

**Issue by thebotherofavatar** [LucasAlegre/sumo-rl#54]
hi, I made an error running sarsa_resco.py and sb3_grid4x4.py in the experiments and pz_test.py in the tests.

![图片](https://user-images.githubusercontent.com/46127899/140029143-a72e1a30-ba85-427e-b100-7bc6fd26f689.png)

**Comment by thebotherofavatar** [comment]
![图片](https://user-images.githubusercontent.com/46127899/140029679-8fe780bc-1381-4d75-a530-5afeec17011c.png)

I really hope I can get some advice and help

**Comment by LucasAlegre** [comment]
It looks like a path error because of Windows. It is not finding the nets directory.

If you use Windows I recommend using WSL with Ubuntu distro.
