### ISSUE TITLE
ModuleNotFoundError: No module named 'stable_baselines3'

### ISSUE THREAD

**Issue by luckywlj** [LucasAlegre/sumo-rl#56]
Hello, I am very interested in your project on reinforcement learning based traffic signal control.I am pleased to find your repository. I download the code, configure the virtual environment, and run the program. But there is an error as follows:
Traceback (most recent call last):
  File "experiments/dqn_2way-single-intersection.py", line 2, in <module>
    from stable_baselines3.dqn.dqn import DQN
ModuleNotFoundError: No module named 'stable_baselines3'
 
I find there is not the folder named stable_baselines in the sumo-rl-master.  Would you pleased to provide the stable_baselines3 directory and its contents?  Thank you so much!

**Comment by LucasAlegre** [comment]
Hi @luckywlj !

stable_baselines3 (https://github.com/DLR-RM/stable-baselines3) is a RL library that you can use in SUMO-RL environments. My repository does not provide the RL algorithms, which you can choose from your preference.

**Comment by luckywlj** [comment]
Thank you so much! I can try it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LucasAlegre/sumo-rl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LucasAlegre/sumo-rl] ModuleNotFoundError: No module named 'stable_baselines3' (Issue #56)





 
Hi @luckywlj !
 
stable_baselines3 (https://github.com/DLR-RM/stable-baselines3) is a RL library that you can use in SUMO-RL environments. My repository does not provide the RL algorithms, which you can choose from your preference.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
