### ISSUE TITLE
Disabling sumo warnings

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#58]
Right now, the log file where I pipe the results of my learning code to to watch is is full of countless sumo warnings, to the point where I can't really read things and see whats going on, like this:

<img width="767" alt="Screen Shot 2021-11-23 at 9 49 21 AM" src="https://user-images.githubusercontent.com/19422700/143046326-cf5c6f33-2dff-48c0-b132-fa9f699ef8aa.png">

How can I disable it?

**Comment by LucasAlegre** [comment]
Hey, I just added a parameter that disables warnings in the constructor 'sumo_warnings=False'. Commit 0c36e0c759defcc5d96301c5af7643e05e987394

**Comment by jkterry1** [comment]
Thanks a ton!
