### ISSUE TITLE
Observation sometimes reached above 1, causing error.

### ISSUE THREAD

**Issue by huyizheng** [LucasAlegre/sumo-rl#6]
I tried to train multiagent model on 4x4grid using c1 route with different algorithms. I simply edit the file `a3c_4x4grid`, change the route file to `nets/4x4-Lucas/4x4c1.rou.xml` and change the num_seconds to 20000.
However, during training, sometimes the observation reached above 1, and the trainer is terminated:
```
ValueError: ('Observation outside expected value range', Box(11,), array([1.        , 0.        , 1.1       , 0.05338078, 0.05338078,
       0.9510391 , 0.9510391 , 0.        , 0.        , 0.9510391 ,
       0.9510391 ]))
```
This only happens randomly (It seems that change the algorithm to PPO will make it easier to reproduce than the default A3C). In this case, only the third place of the observation will exceed 1, and that's the place of `elapsed` (`self.traffic_signals[ts].time_on_phase / self.max_green`).

**Comment by LucasAlegre** [comment]
Thanks for the observation.

I decided not to implement a mechanism like: "if elapsed > max_green then change phase independently of the action chosen by the agent" as in my opinion the max_green time should be learnt by the agent and not imposed.

You can either:

1) Change spaces.Box(low=np.zeros(11), high=np.ones(11)), spaces.Discrete(2) to something like spaces.Box(low=0, high=inf) or spaces.Box(low=0, high=1.2)
2) Do "elapsed = min(1, elapsed)" in compute_observations method.
3) Implement the mechanism mentioned above of changing phase always if the elapsed > max_green

I think the second option makes more sense if you are using a reasonable value por max_green.
