### ISSUE TITLE
No module named 'pettingzoo.utils.conversions'

### ISSUE THREAD

**Issue by Akesukit** [LucasAlegre/sumo-rl#61]
Hi, I have been trying to run "ql_2way-single-intersection.py" on VScode but I have got this issue with pettingzoo module

![image](https://user-images.githubusercontent.com/87381073/143672225-e72910b5-e7be-4d34-a397-4b36a0b58bc5.png)

I'm already installing pettingzoo in Python 3.10.0
but I don't sure that I install it correctly 

Thank so much.

**Comment by LucasAlegre** [comment]
See https://github.com/Farama-Foundation/PettingZoo for installation instructions.
In the readme they say they support Python 3.9, but not 3.10.
