### ISSUE TITLE
'grid4x4' works, but 'cologne3' doesn't in sb3_grid4x4.py

### ISSUE THREAD

**Issue by ryryryy** [LucasAlegre/sumo-rl#62]
I was able to run sb3_grid4x4.py, but when I did the following, it did not work and I got an error. Can you please tell me how to fix it?
```sb3_grid4x4.py
env = sumo_rl.grid4x4(use_gui=True, out_csv_name='outputs/grid4x4/ppo_test')
```
　　　　　　　　　　　　　　　　↓↓↓
```sb3_grid4x4.py

env = sumo_rl.cologne3(use_gui=True, out_csv_name='outputs/grid4x4/ppo_test')
```

Error Message
```
File "/Users/Library/Python/3.7/lib/python/site-packages/supersuit/vector/markov_vector_wrapper.py", line 16, in __init__ ),
 "observation spaces not consistent. Perhaps you should wrap with `supersuit.aec_wrappers.pad_observations`?"
AssertionError: observation spaces not consistent. Perhaps you should wrap with `supersuit.aec_wrappers.pad_observations`?
```

**Comment by LucasAlegre** [comment]
Hi,
In cologne3 the observation and action spaces of the traffic signals are different, so you can't use the same policy for all of them. I'm not sure if this is possible with stable-baselines3. @jkterry1 How did you deal with this in Ingolsdat7?

**Comment by jkterry1** [comment]
eval_env = sumo_rl.ingolstadt7(sumo_warnings=False)
eval_env = ss.pad_observations_v0(eval_env)
eval_env = ss.pad_action_space_v0(eval_env)
eval_env = ss.pettingzoo_env_to_vec_env_v1(eval_env)
eval_env = ss.concat_vec_envs_v1(eval_env, 1, num_cpus=1, base_class="stable_baselines3")

It's using the method in section 5 of https://arxiv.org/abs/2005.13625 to use a single policy
