### ISSUE TITLE
Rendering code crashing due to diverse set of sumo errors

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#67]
Hey,

I'm trying to render a large batch of trained policies using the recently used sumo code, with this file (https://github.com/jkterry1/rl-baselines3-zoo/blob/sumo/run_render2.sh) that calls this file (https://github.com/jkterry1/rl-baselines3-zoo/blob/sumo/render.py). These crashed due to a decent variety of internal sumo errors (logs attached) and crashed so hard that I ended up having to hard reboot my VMs to even access them after the crash. Do you have any idea what's going wrong here?

[render.tar.gz](https://github.com/LucasAlegre/sumo-rl/files/7707551/render.tar.gz)

**Comment by jkterry1** [comment]
the furthest any code code is that run 14 managed to create an empty gif file

**Comment by LucasAlegre** [comment]
Hey,

I took a look at the log files and it seems that the errors all start with the virtual display "grab()" method followed by a MemoryError. I realized that you are using a 5000x5000 resolution, and perhaps this is allocating too much memory. Can you try a lower resolution and check if this solves the problem?

**Comment by jkterry1** [comment]
I'll try that. One debugging question I haven't been able to find an easy answer to- how many frames are in one rollout of ingolstadt 7 or other similar environments?

**Comment by LucasAlegre** [comment]
The number of steps can be calculated as `(num_seconds - begin_time)/delta_time`. In this case, `720 steps = (61200-57600)/5` for Ingolstadt.

**Comment by jkterry1** [comment]
So, I just sat down and after more changes, either I'm an idiot or there's behavior resembling a memory leak going on here. I'm using [this file](https://github.com/jkterry1/rl-baselines3-zoo/blob/sumo/render.py) for rendering. I reduced it to 4000x4000 for testing purposes, but huge resolutions really are needed for this stuff to be intelligible because the rendering sucks. The total buffer of frames in RAM to turn into a gif should be 4000x4000x720 bytes (11.52GB). So far on my machine, this process has managed to consume over 100GB of RAM and is growing. I can sit down and do more debugging on this later, but this clearly should not be happening.

**Comment by LucasAlegre** [comment]
Isn't 4000x4000 still too much? I tested with a 500x500 resolution and generated a video with ffmpeg and everything was intelligible.
Anyway, strange that it is consuming over 100GB, perhaps the frames are staying in memory after you save to disc.

**Comment by RedTachyon** [comment]
@LucasAlegre What map did you use with the 500x500 resolution? With any moderately large ones that I tried (Ingolstadt7 and grid4x4 mainly), the cars are super small.

**Comment by LucasAlegre** [comment]
> @LucasAlegre What map did you use with the 500x500 resolution? With any moderately large ones that I tried (Ingolstadt7 and grid4x4 mainly), the cars are super small.

Sorry, I was mistaken. You are right, 500x500 does not give good results :(

**Comment by LucasAlegre** [comment]
> So, I just sat down and after more changes, either I'm an idiot or there's behavior resembling a memory leak going on here. I'm using [this file](https://github.com/jkterry1/rl-baselines3-zoo/blob/sumo/render.py) for rendering. I reduced it to 4000x4000 for testing purposes, but huge resolutions really are needed for this stuff to be intelligible because the rendering sucks. The total buffer of frames in RAM to turn into a gif should be 4000x4000x720 bytes (11.52GB). So far on my machine, this process has managed to consume over 100GB of RAM and is growing. I can sit down and do more debugging on this later, but this clearly should not be happening.

Perhaps instead of saving every frame into a list and then making a gif, you could try to save every frame to disc and generate the gif in another process, so your ram will store only one frame at a time.

**Comment by LucasAlegre** [comment]
@RedTachyon @jkterry1 
I have just found out that you can visualize the vehicles bigger when zooming out, perhaps solving the problem you had with the vehicles being too small. See min 8:00 of https://www.youtube.com/watch?v=urKtJj87X5M.
