### ISSUE TITLE
CSV files are corrupted in multiprocess environment

### ISSUE THREAD

**Issue by talha1223** [LucasAlegre/sumo-rl#7]
Hi, First of all thanks for this excellent work.

I have observed that when using the multi-process environment, different threads tried to write files at a same time and in a result the csv files are fully redundant. 

The problem can be solved by using the simple environment or by setting the n_cpu argument to 1 in a vectorized environment. But is there any way to resolve the problem while keeping the same vectorized environment with multiple threads.?

Thanks

**Comment by LucasAlegre** [comment]
Hello, thank you very much!

I believe it could be solved by passing a different name for "out_csv_name" on each instance of the environment in the vectorized env. Then you would get a different csv for each thread.

Does it works for  you?

Regards,
Lucas

**Comment by Talha-123874** [comment]
Hi, Thanks for your reply. 

I have tried it also but I didn't work for me (at least). I could only be able to do this by using the Python Tkinter library where every time program stop and I could specify the location where I want to save and indeed this is not a optimal way.

Maybe my approach is not correct or maybe there is something which I'm not getting now.
If it works for you, it would be very much helpful if you can mention here. 

Thanks again,
Regards,
Talha

**Comment by talha1223** [comment]
Its hard to pass a different name for "out_csv_name" on each instance of the environment in the vectorized env with the Lambda expression. One possible solution might be not to use the Lambda expression in vectorized env, and create a utility function for multiprocessed env  same as defined in SB (screenshot attached below)

![SB](https://user-images.githubusercontent.com/44058353/68741553-e47bd280-0628-11ea-898e-156b8343990e.png)

Best, 
Umer

**Comment by LucasAlegre** [comment]
Thank you! 
This is definitely the best solution :)
