### ISSUE TITLE
New warning congesting logs

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#72]
Hey, I'm doing more work trying to get my video generation code working, and I'm getting so much of this warning that it's causing issues reading logs:

`/home/j_k_terry/sumo-rl/sumo_rl/environment/traffic_signal.py:59: UserWarning: Call to deprecated function getCompleteRedYellowGreenDefinition, use getAllProgramLogics instead.`

Do you happen to know what the problem is?

**Comment by LucasAlegre** [comment]
Hey! Strange that I do not get this warning. Anyway, I just replaced 'getCompleteRedYellowGreenDefinition' by 'getAllProgramLogics' in the last commit. This should solve.

**Comment by jkterry1** [comment]
Thanks a ton!
