### ISSUE TITLE
Rendering FPS

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#73]
Hey,

Do you know what FPS the SUMO environments run at/should be rendered at? After looking for around for awhile it's not obvious to me.

**Comment by LucasAlegre** [comment]
Hey,

Every simulation step corresponds to 1 second of "real life". So if you want video at normal speed it would be 1 fps. This would be too slow to watch off course, so you can increase the fps as you want when generating the video.
