### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'outputs

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [LucasAlegre/sumo-rl#78]
Hello

When I ran 02 file ql_single-intersection and ql_2way-single-intersection , the program started but the result file was not found. 
OSError: [Errno 22] Invalid argument: 'outputs/single-intersection/2022-01-07 10:39:15_alpha0.1_gamma0.99_eps0.05_decay1.0_conn0_run1.csv'
Step #1005.00 (0ms ?*RT. ?UPS, TraCI: 31ms, vehicles TOT 541 ACT 41 BUF 0)

Which this file ql_4x4grid, I saw the result.

I would like to ask you ask how to save the trained model and run it again?
Thanks

**Comment by LucasAlegre** [comment]
Hi,

This is because you are using Windows and the file name contains "." chars. You should just rename the output file to avoid this error in Windows.

I did not implement save/load for tabular Q-learning, but this should be simple to implement using pickle library.
Cheers!
