### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Eden1114** [LucasAlegre/sumo-rl#81]
Hello Everyone, I really enjoy using this repo for my RL experiments. Thanks a lot to the authors.

During using this repo, I find some problems in the `setup.py` file, which makes the sumo-rl can not be installed through 
`python setup.py install` and `pip install sumo_rl` correctly.

I forked this repo and modified the code to the correct [version.](https://github.com/eden1114/sumo-rl)

(There may have some problem with RESCO .xml files, since it was imported through a PATH directly in the [code](https://github.com/LucasAlegre/sumo-rl/blob/0bba6f1eb8c4fa8b6b1b21bf034ed2f26e14d81c/sumo_rl/environment/resco_envs.py#L5).)

I am considering to push a merge request to fix the problem after I finish the RESO envs.

```Python
from setuptools import setup, find_packages

REQUIRED = ['gym', 'numpy', 'pandas', 'pillow', 'pettingzoo']

extras = {
    "rendering": ["pyvirtualdisplay"]
}
extras["all"] = extras["rendering"]

setup(
    name='sumo-rl',
    version='1.1',
    packages=find_packages(),
    install_requires=REQUIRED,
    extras_require=extras,
    include_package_data=True,
    author='LucasAlegre',
    author_email='lucasnale@gmail.com',
    url='https://github.com/LucasAlegre/sumo-rl',
    download_url='https://github.com/LucasAlegre/sumo-rl/archive/v1.0.tar.gz',
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    license="MIT",
    description='RL environments and learning code for traffic signal control in SUMO.'
)
```

**Comment by LucasAlegre** [comment]
Closing as I believe this is already solved.
