### ISSUE TITLE
Newest versions of gym and pettingzoo

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#82]
Hey, when you get a chance could you please bump the versions of gym and pettingzoo you're depending on to the newest and make the corresponding API changes? There's been several updates since you last did this.

**Comment by LucasAlegre** [comment]
Hi,

I installed the latest versions of gym and pettingzoo and all tests keep passing. I only had to add a **kwargs argument to the reset method in 0bba6f1eb8c4fa8b6b1b21bf034ed2f26e14d81c .

Are there any API changes not covered by the tests? Thanks!

**Comment by jkterry1** [comment]
If tests keep passing that's the only thing you should've certainly had to add, though thats slightly less than I expected to have to be changed :)
