### ISSUE TITLE
Problem when using new network file

### ISSUE THREAD

**Issue by DryCell-x** [LucasAlegre/sumo-rl#83]
Hi, I'm currently using sumo-rl for new network file other than network files available in your depository. The network is consist of 20 traffic light (tl) junction. when i run the program, i got this error : 
![image](https://user-images.githubusercontent.com/101935535/160357209-e452c4c9-c00a-40a7-9690-a642d88d01bf.png)

(AttributeError: 'int' object has no attribute 'items') 
Any idea what is went wrong?

**Comment by LucasAlegre** [comment]
Hi,

It seems your algorithm is passing an 'int' instead of a 'dict' to the env.step method. When the scenario is multi-agent you should pass a dictionary containing the actions of each agent.

**Comment by DryCell-x** [comment]
Ah i see. Thank you very much for your response.
