### ISSUE TITLE
Error when running fixed time simulation

### ISSUE THREAD

**Issue by DryCell-x** [LucasAlegre/sumo-rl#84]
Hi, currently i am try to run fixed-time simulation (fixed_ts = True) in traffic network consisting 30 intersection using sumo-rl. But i get this following error.
![image](https://user-images.githubusercontent.com/101935535/163814175-5f055a91-49a3-438f-bfc7-f8df7c29186d.png)
It looks like the environment fail to provide an action from <tl logic> list which is defined in net.xml file. Any idea how to fix it?

**Comment by marwaelharoun** [comment]
> Hi, currently i am try to run fixed-time simulation (fixed_ts = True) in traffic network consisting 30 intersection using sumo-rl. But i get this following error.


Hi, 
I have the same problem, but where can I change the step method to none?
