### ISSUE TITLE
How does the num_seconds parameter differs from timesteps?

### ISSUE THREAD

**Issue by EvanMath** [LucasAlegre/sumo-rl#87]
Hello @LucasAlegre 

I am trying to understand how `timesteps` in training and `num_seconds` env's parameter relate to each other. I think they relate to each based on the `delta_time` env's parameter, is that correct?

And one more question, I noticed that the plot actually averages the metrics of each episode in the simulator (100000 num_seconds), why did you choose to plot this? And how do the "reward" and the "total_wait_time" differ?

**Comment by LucasAlegre** [comment]
Hi!

> I am trying to understand how `timesteps` in training and `num_seconds` env's parameter relate to each other. I think they relate to each based on the `delta_time` env's parameter, is that correct?

Exactly. 1 timestep for the agents correspond to `delta_time` seconds in the simulation.

> And one more question, I noticed that the plot actually averages the metrics of each episode in the simulator (100000 num_seconds), why did you choose to plot this? And how do the "reward" and the "total_wait_time" differ?

This is useful not to average the episodes, but to average multiple equal runs with different seeds. The reward is the "change" in waiting time (as defined in the README).

**Comment by LucasAlegre** [comment]
> As I am starting now with SUMO, I would like to ask, how does the seed affect the simulator?

See https://sumo.dlr.de/docs/Simulation/Randomness.html

> Is it possible to change the traffic volume (which I think is defined when we create the roadnet)? I haven't found in SUMO documentation something related to `seed`.

Yes, the traffic flows are defined in the .rou.xml file.

> I was thinking of turning it to a negative value because an agent tries to maximize its reward thus a negative value in the change of waiting time should drive the agent to actually minimize it. But now makes sense, cool. So maximizing the change means that the future waiting time will be smaller. Thus, the waiting time will go to 0. Is that correct?

Exactly!

**Comment by EvanMath** [comment]
Thank you for these clarifications!
