### ISSUE TITLE
problem of the depandency of a3c_4x4grid.py 

### ISSUE THREAD

**Issue by luckywlj** [LucasAlegre/sumo-rl#89]
Hi, the depandency of a3c_4x4grid.py  is rllib. I download the rllib according to  the link of README. But when I run the a3c_grid4x4.py, I check the errors and find there is no modules and folders which is imported in the a3c_grid4x4.py. Could you please give the useable rllib version or link?

**Comment by LucasAlegre** [comment]
Hi, can you share the error messages?

**Comment by luckywlj** [comment]
I check the README and install dependency packages once again.  It is OK.  It is my problem of installation.
