### ISSUE TITLE
The training process may not work if I remove --max-depart-delay setting in sumo

### ISSUE THREAD

**Issue by sxyd** [LucasAlegre/sumo-rl#9]
When I run `a3c_2way-single-intersection.py`, if I remove the line `'--max-depart-delay', str(self.max_depart_delay),` in `env.py`, the total waiting times are still around 3000 at step 10000 that is inconsistent with the results in this repository. I wonder if it means that the training process does not work for the scenario.

My plotted results:
![image](https://user-images.githubusercontent.com/10708371/80915207-6a303d80-8d83-11ea-9d39-af6c429d22be.png)

**Comment by LucasAlegre** [comment]
Hi,

Have you compared your results with --max-depart-delay uncommented?
I think the results may be different because of the .rou file, which could have been modified to add more vehicles.

**Comment by sxyd** [comment]
The results with --max-depart-delay uncommented is similar with that in the example of this repository.
![image](https://user-images.githubusercontent.com/10708371/81027810-abbf0680-8eb1-11ea-8481-1981f34956b8.png)

But I find that the episode average reward still increase along with the training process with  max-depart-delay commented. (In this experiment, the num_seconds parameter is set to 3600 to examine the episode reward in rllib.)
![image](https://user-images.githubusercontent.com/10708371/81028009-58998380-8eb2-11ea-95a7-1846efc74996.png)

So the training still works with --max-depart-delay commented but the influence on total waiting times is less than that with the setting of max-depart-delay=0. 

The setting max-depart-delay=0 means that vehicles are discarded if they could not be inserted after 0 second  as the sumo document shows. So the RL agent may tend to increasing the total reward by letting sumo decrease the inserted vehicles number during training process rather than dispatching vehicles in an efficient way.

**Comment by zzcNEU** [comment]
hello,I want torun it. But, something occurs,

ImportError: Ray must be imported before pickle5 because Ray requires a specific version of pickle5 (which is packaged along with Ray).

And, my ray is 0.8.5, pickle5 0.0.9, I add the" import pickle5" in the start. It still occurs, Import error.
