### ISSUE TITLE
minimum green light time #I need some help

### ISSUE THREAD

**Issue by TailongSong202064524** [LucasAlegre/sumo-rl#90]
Hey,I have some problems that I can't solve by myself.Hope you can help me see how to fix it.

1. dqn_2way-single-intersection.py : episodes = 4，I didn't find where to set it;
2. I want to set different minimum green light time for different agents, how to set it?

My python level is relatively poor, so there are many problems caused by myself. I'm sorry to take up your personal time. I hope you can reply to me after seeing my message, thank you.

**Comment by LucasAlegre** [comment]
Hi!

> Hey,I have some problems that I can't solve by myself.Hope you can help me see how to fix it.
> 
> 1. dqn_2way-single-intersection.py : episodes = 4，I didn't find where to set it;
>
Please check the stable-baselines3 documentation to configure the parameters of the learning algorithm.

> 2. I want to set different minimum green light time for different agents, how to set it?
> 
Unfortunately, this is currently not possible, but should be easy add this feature.

**Comment by TailongSong202064524** [comment]
It’s very kind of you to help me.thank you very much
