### ISSUE TITLE
a3c_4x4grid running issue

### ISSUE THREAD

**Issue by Sitting-Down** [LucasAlegre/sumo-rl#94]
Hello Im a student who has taken an interest in Machine Learning and tried to learn more about multi-agent env so I tried to run your a3c_4x4grid but I couldnt seem to get it to work?
There was an initial error that cascaded when trying to handle it.
I would like help if possible in resolving it, thank you!
Im using Python 3.9 if that changes anything
![image](https://user-images.githubusercontent.com/105152125/175265886-ad612bad-25df-45c0-9ead-b01ca3ca9867.png)
![image](https://user-images.githubusercontent.com/105152125/175265973-6468696a-ebb2-44ba-8ae5-abec4da35398.png)
![image](https://user-images.githubusercontent.com/105152125/175266067-7aab9fad-14c5-4202-9593-7d1b50377116.png)
![image](https://user-images.githubusercontent.com/105152125/175266199-2b8e731e-7d48-4a09-aa7d-719efd994b03.png)

**Comment by LucasAlegre** [comment]
Hi,

Can you try updating PettingZoo and ensuring gym is version 0.24.0?

**Comment by thoithoi58** [comment]
I faced the same issue, the solution is to install these version:
- pettingzoo==1.15.0
- supersuit==3.3.3
- gym=0.22.0
Hope it help!

**Comment by Sitting-Down** [comment]
That fixed the issue thank you!
