### ISSUE TITLE
Multiple results in A3C for grid4x4 using ray rllib

### ISSUE THREAD

**Issue by ngctnnnn** [LucasAlegre/sumo-rl#95]
While using `a3c_4x4grid.py`, I received 4 csv files as the outputs. I'm not sure whether these output files are served as different runs for the algorithm or not. And if I just want to receive only 1 csv output file only, how could I fix that ?

![286737001_1012775282717309_4399072559773242496_n](https://user-images.githubusercontent.com/67086934/175759670-4c8b3ffe-d863-417f-b543-e771c42ae019.png)

**Comment by LucasAlegre** [comment]
Each csv file corresponds to a different episode, i.e. the metrics until the simulation ends.

**Comment by ngctnnnn** [comment]
I see. But what could I do so that my algorithm produces 1 csv file only ?

**Comment by TrinhTuanHung2021** [comment]
> I see. But what could I do so that my algorithm produces 1 csv file only ?

Hello. you can use Python to get the waiting time in each episode and create a new graph
