### ISSUE TITLE
Version Bumps

### ISSUE THREAD

**Issue by jkterry1** [LucasAlegre/sumo-rl#99]
Hey,

Could you please make sure you're passing compliance tests for the newest versions of Gym and PettingZoo?

**Comment by LucasAlegre** [comment]
Hey, sure! It will probably take some time, though. I am moving to Europe next week.

**Comment by LucasAlegre** [comment]
@jkterry1, both gym==0.25.1 and pettingzoo==1.20.1 tests are passing at the current state of the repo :)

**Comment by TrinhTuanHung2021** [comment]
> @jkterry1, both gym==0.25.1 and pettingzoo==1.20.1 tests are passing at the current state of the repo :)

Hello, with gym==0.25.1 i had errors when running a3c_4x4grid.py
AttributeError: module 'gym.wrappers' has no attribute 'Monitor'.
They have changed and removed the Monitor since 0.23

**Comment by LucasAlegre** [comment]
> > @jkterry1, both gym==0.25.1 and pettingzoo==1.20.1 tests are passing at the current state of the repo :)
> 
> Hello, with gym==0.25.1 i had errors when running a3c_4x4grid.py AttributeError: module 'gym.wrappers' has no attribute 'Monitor'. They have changed and removed the Monitor since 0.23

This seems like incompatibility in the ray library. Check the ray version and whether it is compatible with the gym version we are using.
